### ISSUE TITLE
listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by yogi2806** [phonegap/phonegap-app-desktop#538] opened 2016-02-10 07:54 UTC
Once after creating project am not able to go forward it keeps showing me error has " listen EADDRINUSE :::3000 ". I tried to change port and also disabled all proxies but still no help.

**Comment by hermwong** [comment] 2016-02-10 20:13
Duplicate of #532. Locking this issue to keep all discussion centralized in #532.

**Closed by hermwong** 2016-02-10 20:13 UTC
Labels: bug, duplicate
