### ISSUE TITLE
it just keeps loading on loop

### ISSUE THREAD

**Issue by jakobgibbs555** [phonegap/phonegap-app-desktop#914] opened 2020-01-05 18:33 UTC
## _System Configuration_
I don't know /na
### PhoneGap Desktop version
the one on phonegap.com
### PhoneGap Mobile App version
the newest
### Mobile devices & Mobile OS version
moto z2, android version 8.0.0
### Computer OS version
windows 10
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
acer nitro 5 laptop, no anti virus, firewall or disk encryption
### Are you using VMs on your computer?
I don't know what a vm is
### Do you have multiple network adapters (or virtual network adapters)?
no
### Are you using VPN?
no
### Expected Behaviour
the app loads
### Actual Behaviour
it keeps loading on
### Steps to Reproduce 
open phonegap on desktop
#### Error messages
na

**Comment by JFDonovan** [comment] 2020-01-06 15:26
Same issue, infinite loading screen (not white, but the circular loading icon that spins).

**Comment by TheGeniusCoder** [comment] 2020-01-12 04:21
same for me

**Comment by gtmsingh** [comment] 2020-01-28 18:10
Issue is resolved in discussion of this: #913 

Duplicate of #913

**Comment by baberzaman** [comment] 2020-04-22 12:28
Same for me as well. I have tried Installing from Installer and As well As from Github ZIP. Same Loading icon for hours really.

**Closed** 2020-12-19 08:00 UTC
Labels: wontfix
