### ISSUE TITLE
Error launching server

### ISSUE THREAD

**Issue by sashabrava** [phonegap/phonegap-app-desktop#759] opened 2017-01-07 11:37 UTC
### PhoneGap Desktop version
v 0.4.2
### Computer OS version
Window 10 64 bit
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
anti-virus ESET NOD32
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
yes, virtual network adapter
### Are you using VPN?
no
### Expected Behavior
To get server running on necessary port.
### Actual Behavior
Error launching server on laptop.
### Steps to Reproduce 
Launch app twice, and try to launch the project (projects) in both launched apps. Project will be launched successfully in 1st program, but the error appears in 2nd. Problem also might appear after the laptop got into hibernation (firstly the bug was discovered because the process of program wasn't killed after the app was closed. So, when I launched the app again, hours later, I had only one app launched on panel, but Task Manager showed it like there are 2 PhoneGap apps running on PC)
#### Error messages
listen EADDRINUSE :::3000
![phonegap](https://cloud.githubusercontent.com/assets/11160215/21741429/7a9f815c-d4e6-11e6-87ec-58e72b29c68d.JPG)

**Comment by surajpindoria** [comment] 2017-01-09 18:27
Hi @sashabrava,

If my understanding is correct, you are trying launch two instances of the desktop app and serve a project, then this is not a bug. You cannot use the same port twice to serve a project, hence why you are getting this error message.

If you want to launch two instances of the desktop app, you will need to change the port on one to something else and it should be fine.

**Comment by sashabrava** [comment] 2017-01-10 14:05
Hi, @surajpindoria 

Yes, you understood me clear. 👍 

So - running 2 instances of PhoneGap desktop app it is not a bug! It's feature, that allows to run several projects simultaneously on different ports! Right?

Then... Then I have found a bug in this feature  - when I start 2 projects (even different ones) on different ports, they start to update each several seconds, that makes impossible to test them both at the same time. And this forced update continues until I don't stop one of this projects. 

If my idea is  unclear, I can record a screen video to show what exactly I mean.

**Comment by surajpindoria** [comment] 2017-01-10 17:51
Can you post a video please, I am having a hard time trying to visualize what is actually going on.

Also, why do you need to run two instance of the desktop app? Do you need to test both projects at the same time? This is not really the intended use case for the app and therefore something may be getting messed up because of that.

**Comment by sashabrava** [comment] 2017-01-11 17:45
https://www.dropbox.com/s/7eltok0c3kjs06b/phonegap_compressed.avi?dl=0
That's a link on video.

I don't need to launch 2 instances of app. I just accidentally noticed that the app misbehaves if I try to launch it in 2 instances - but nevertheless the app allows users to repeat these steps and to be "broken" this way.

That's why I decided to inform you about it.

**Comment by surajpindoria** [comment] 2017-01-11 19:04
I understand what you are saying now, thanks or the video! You are correct that this a bug but it is actually a problem with either the phonegap CLI or `connect-phonegap` module. I will continue to investigate.

Leaving this open for now until I can track where the bug actually lies, then I will file it in the appropriate place.

**Comment by sashabrava** [comment] 2017-01-11 19:40
Not at all.

Hope it will help you to improve the app.

**Comment by pabloe1981** [comment] 2017-01-12 00:26
a mi en windows 7 32bits no me brinda la ip, para establecer la conexión con el celular

**Comment by sashabrava** [comment] 2017-01-12 10:41
@pabloe1981 
Try to open the project in browser of your computer. If it will open, it means that the PhoneGap works correct and you have a problem with connection on your phone. If not, try to change the port and check if the IP address PhoneGap gives to you is not busy on your port.

**Comment by surajpindoria** [comment] 2017-05-03 20:51
Going to close this as it is related to the CLI and connect-phonegap.

**Closed by surajpindoria** 2017-05-03 20:51 UTC
Labels: Connect-PhoneGap, PhoneGap CLI, user support
