### ISSUE TITLE
Big Fuckin* Problem with Connection.

### ISSUE THREAD

**Issue by hayg** [phonegap/phonegap-app-desktop#564] opened 2016-03-01 03:40 UTC
I'm trying to connect my PC which has Windows 10 with my iPhone 6
But on the phone screen I just see an ERROR like this "unable to download archive from this server" and "Please enter a valid url to connect to." I've checked the IP address for thousand times but nothing changed
PLEASE HELP ME SOS!!!!! 
@PhoneGap Developer Mobile App @PhoneGapCI

**Comment by hermwong** [comment] 2016-03-01 21:26
Duplicate of #566. Closing and locking this issue.

**Closed by hermwong** 2016-03-01 21:26 UTC
