### ISSUE TITLE
Not able to connect to the phonegap server

### ISSUE THREAD

**Issue by navcfc** [phonegap/phonegap-app-desktop#436] opened 2015-09-02 16:52 UTC
Hi I tried all possible ways of connecting to the server that is mentioned in the phonegap desktop app. Be it from an android app or be it copying the ip address onto chrome and testing out. It only says Connection Timed out. And not able to connect no matter what. I did check some of the previous threads regarding this, tried everything that was mentioned but to no avail. had no other option but to create a new issue thread, sorry about that. but i need to fix this as soon as possible. 
Thanks a lot for understanding!

**Comment by RajputVivek** [comment] 2015-09-02 18:52
Same here, updated the app, the developer mobile app, tried to download the zip folder on phone's chrome...nothing worked.

**Comment by edenprojectde** [comment] 2015-09-06 21:41
0.1.9 Desktop and latest Mobile App are compatible
The Version on the site(0.1.2) doesn't seem to work with the Mobile App

**Comment by djsmithme** [comment] 2015-09-08 14:04
I had a a connection problem on Yosemite. 

Turned out I had an issue with my network connection lo0 - OpenVPN had created a loopback which was stopping the Desktop app from connecting.

**Comment by hermwong** [comment] 2015-09-08 16:30
Duplicate of issue: https://github.com/phonegap/phonegap-app-desktop/issues/432

**Closed by hermwong** 2015-09-08 16:30 UTC
Labels: duplicate, user support
