### ISSUE TITLE
errors related to config.xml

### ISSUE THREAD

**Issue by Devleaf-IT** [phonegap/phonegap-app-desktop#763] opened 2017-01-13 17:09 UTC
## _System Configuration_
Win 10 - i5 6600 - 16gb DDR3 RAM - 1tb SSHD, 1tb HDD, 128gb SSD, GTX 1060
MacOS - Late 2014 macbook pro, 8gb RAM, i5 

### PhoneGap Desktop version
0.4.3
### PhoneGap Mobile App version
N/A
### Mobile devices & Mobile OS version
N/A
### Computer OS version
Win 10, MacOS
### Network Type (home/corporate)
Home
### Is your network using a proxy?
No
### Computer / Network security (firewall / anti-virus / disk encryption)
Avast Anti virus on windows, None on Mac
### Are you using VMs on your computer?
No
### Do you have multiple network adapters (or virtual network adapters)?
No
### Are you using VPN?
No
### Expected Behaviour
Phonegap Allows me to add existing projects after update
### Actual Behaviour
Phonegap results in nothing being added, regardless of drag & drop or adding through the dropdown
### Steps to Reproduce 
Updating to 0.4.3 created this issue.
#### Error messages
N/A although creating a new project results in error code 1 (already identified as a bug)
#### Other Notes
After downgrading again to 0.4.2/0.4.1, the problem isn't resolved still. It persists after downgrading.
Bug fixes attempted:
- Re-installing phonegap 0.4.3
- Downgrading to 0.4.2/0.4.1
- Wiping the .cordova directory and restarting
- Wiping the Local Storage folder and restarting
- Disabling anti-virus where possible.
I have now resulted to CLI, but was just making this issue aware if it is a system wide problem.

Thanks,

Matt
devleaf.com

**Comment by hermwong** [comment] 2017-01-13 18:24
I tried to reproduce this issue with a fresh install of 0.4.3 but wasn't able to get the errors reported.

I was able to add an existing project and also able to create a new project without any errors.

Is there anymore details that can think of that might help us figure this out?

**Comment by surajpindoria** [comment] 2017-01-13 20:39
I have also tried this on both Mac and Windows and could not reproduce the issue.

Are you able to create new projects fine?

**Comment by Devleaf-IT** [comment] 2017-01-13 20:50
@hermwong @surajpindoria 
Think i may be onto the problem, i can create new projects fine, but running phonegap CLI on my existing project gives "parsing D:\<LOCATION>\config.xml failed".

Could this be the issue?

**Comment by surajpindoria** [comment] 2017-01-13 21:03
Are you running a specific command that produces this error or it is happening with all commands?

**Comment by Devleaf-IT** [comment] 2017-01-13 21:05
@surajpindoria only tried the 'phonegap serve' command at the moment, and it's giving me the warning then, although it still runs the server correctly and allows me to access it through the phonegap developer app.

**Comment by surajpindoria** [comment] 2017-01-13 21:39
Looks like you have an issue with your xml. On lines 22-24 you have:
```
<plugin name="phonegap-plugin-barcodescanner" source="npm" />
    <variable name="CAMERA_USAGE_DESCRIPTION" value="Used for access to QR system." />
</plugin>
```
The "/" at the end of the first plugin tag is incorrect since you are trying to close the tag after adding a variable attribute.

**Comment by Devleaf-IT** [comment] 2017-01-13 21:56
@surajpindoria Issue sorted, but i don't know why it hasn't happened before.

I has the wrong config.xml in, however the problem was that in my updated one, i received the error:

> cp: no such file or directory: D:\<directory>\res\screen\ios\iphone6p.png

However my res folder was (and always has been) inside my \www\ directory, which would be:
D:\<directory>\www\res\screen\ios\iphone6p.png.

Any idea as to why it has been working so long without problem? My file structure was as follows

ROOT
- hooks
- platforms
- plugins
- www
-- My code
-- res
-- spec
-- icon.png
-- splash.png
- config.xml

**Comment by hermwong** [comment] 2017-01-17 19:05
Project structure should follow the structure shown in the [PhoneGap Build docs](http://docs.phonegap.com/phonegap-build/getting-started/app-project-structure/)

**Comment by surajpindoria** [comment] 2017-05-03 20:52
Going to close this as it seems to have been resolved.

**Closed by surajpindoria** 2017-05-03 20:52 UTC
Labels: user support
