### ISSUE TITLE
Phonegap Desktop for Linux

### ISSUE THREAD

**Issue by batalvi** [phonegap/phonegap-app-desktop#397] opened 2015-07-13 22:27 UTC
Is there a version of Phonegap Desktop for Ubuntu 14.01. Thanks.

**Comment by hermwong** [comment] 2015-07-14 18:39
Duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/249

**Closed** 2015-07-14 18:38 UTC
Labels: duplicate

**Comment by jrortiz8585** [comment] 2015-07-15 15:59
the version for linux ubuntu 14.x

**Comment by pontume1** [comment] 2017-01-05 06:44
+1 Ubuntu
