### ISSUE TITLE
Stuck at loading screen

### ISSUE THREAD

**Issue by jacob-j** [phonegap/phonegap-app-desktop#604] opened 2016-04-19 09:38 UTC
Hello!

My Phonegap desktop app is stuck at loading screen. It happened when I reinstalled 0.3.0.

PhoneGap Desktop version / PhoneGap CLI version: **0.3.0**
Computer OS version **10.11.4** (15E65)
network type (home/corporate) **Home**
computer / network security (firewall / anti-virus / disk encryption) **OS X built in Firewall. FileVault off**
are you using VMs on your computer? **No**
do you have multiple network adapters (or virtual network adapters) **No**
are you using VPN? **No**

**Comment by mk48** [comment] 2016-04-19 15:26
@jacob-j  me too facing the same issue in the latest version 0.3.0 
https://github.com/phonegap/phonegap-app-desktop/issues/597

**Comment by ray-moncada** [comment] 2016-04-19 16:29
same issue here. Using CLI instead.

**Comment by rgalipeau** [comment] 2016-04-19 16:36
Same thing here. I tried to give SUDO to the app directly... Get this error in the terminal when it boots;

me$ sudo "/Applications/PhoneGap.app/Contents/MacOS/Electron"
(electron) loadUrl is deprecated. Use loadURL instead.
(electron) setFeedUrl is deprecated. Use setFeedURL instead.

**Comment by RubenDorrego** [comment] 2016-04-19 17:02
Same problem here, it hangs forever with loading animation, please fix it ASAP. I'm running in Windows 10 64 bits, installed few hours ago with only MS Office and few utilities.

**Comment by hermwong** [comment] 2016-04-19 18:21
hi all,

It would help us troubleshoot if you could provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by hermwong** [comment] 2016-04-19 18:25
Hi @jacob-j have you tried it with your firewall disabled?

**Comment by RubenDorrego** [comment] 2016-04-19 18:30
Answers:
**    PhoneGap Desktop version / PhoneGap CLI version:**  PhoneGap Desktop version 0.3
**    PhoneGap Mobile App version** Android 1.6.0, Iphone 1.6.2 
    **Mobile devices & Mobile OS version** The issue is in the desktop tool BEFORE load any project. Previous version of Phonegap Desktop 0.2.3 works like a charm in same PC. We just tested again.
    **Computer OS version** Windows 10 Enterprise  64bits
    **network type (home/corporate)** Home
   ** is your network using a proxy?** NO
    **computer / network security (firewall / anti-virus / disk encryption)** Windows Firewall, No additional Antivirus. 
    **are you using VMs on your computer?** NO
    do you have multiple network adapters (or virtual network adapters) NO, We are connected to the router using the default cable connector , no wireless devices, No extra network adapter.
    are you using VPN? NO

**Comment by RubenDorrego** [comment] 2016-04-19 18:36
Finally is working!
I just did these steps
1-) uninstall 0.3 
2-) install 0.2.3
3-) Check everything is ok
4-) Disable firewall
5-) Uninstall 0.2.3
6-) Install 0.3
7-) Check everything is ok!
8-) Enable Firewall and check again. All good!

**Comment by rgalipeau** [comment] 2016-04-19 18:38
@hermwong 
Tested on 5 different macs both from employee home offices and corporate office, all form ranging mac os, same experience for each (and they are all slightly different).
no VPNs or proprietary set-ups.

**Comment by raysango** [comment] 2016-04-19 20:10
me too facing the same issue with v0.3.0 on a mac with OS 10.10.5, v0.2.3 is working

**Comment by dominuspolux** [comment] 2016-04-19 21:30
Same issue here. Windows 7 ultimate x86, clean install, no firewall. Phonegap desktop 0.3.0

**Comment by bryandease** [comment] 2016-04-19 21:39
Same issue here - OSX 10.11.4 - no antivirus - no VPN

**Comment by hermwong** [comment] 2016-04-19 22:16
I haven't been able to reproduce the issue on my OSX (10.14.4) or Windows 10 x64 virtual machine. I've had a couple of users report work arounds to get PhoneGap Desktop 0.3.0 past the stuck loading screen.

Please see the instructions below & let me know if this solution works for you.

We are still troubleshooting to determine the root cause of this issue and we thank you (our users) for your patience.

### Windows users:

@RubenDorrego mentioned that he was able to get PhoneGap Desktop 0.3.0 to work on Windows by [uninstalling and then reinstalling](https://github.com/phonegap/phonegap-app-desktop/issues/604#issuecomment-212061622).

1. using Window's add/remove software feature uninstall PhoneGap Desktop
1. download 0.3.0 from [PhoneGap Desktop release page](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.0)
1. run the `PhoneGapSetup-win32.exe` to re-install

### OSX users:

This user was able to get PhoneGap Desktop 0.3.0 to work on [OSX by removing the `.plist` files](https://twitter.com/apt/status/722494866626908161).

1. delete PhoneGap Desktop from your Applications folder
1. download `PhoneGap-Desktop-Beta-0.3.0-mac.zip` from [PhoneGap Desktop release page](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.3.0)
1. unzip the `.zip` file
1. copy PhoneGap into your Applications folder

**Comment by bryandease** [comment] 2016-04-19 22:37
@hermwong Tried the OSX users fix.  Still same issue.  Nothing but spinning circle still.

**Comment by hermwong** [comment] 2016-04-19 22:39
@bryandease, thanks for verifying that for us!

**Comment by ryoniebalonie** [comment] 2016-04-19 22:57
I too have removed and reinstalled several times with no luck. Unfortunately if you install an older version it automatically updates to 0.3.0. Thanks for working on a fix!

**Comment by hermwong** [comment] 2016-04-19 23:25
I've compiled a version of PhoneGap Desktop 0.2.3 for OSX that won't auto-update. This should allow OSX users to continue using PhoneGap Desktop while we continue working on this issue.

[Download `PhoneGap-Desktop-0.2.3-mac-non-auto-update.zip`](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.2.3/PhoneGap-Desktop-0.2.3-mac-non-auto-update.zip).

**Comment by ryoniebalonie** [comment] 2016-04-19 23:50
awesome.

**Comment by jacob-j** [comment] 2016-04-20 07:08
Here is quick fix for OS X users:
Navigate to `/Users/your_user_name/Applications/Phonegap/Contents/Resources/app/index.html`

Add this code at line 318. Make sure its inside the `<script>` tags.

```
        $(window).on("load", function () {
            $("#loading-overlay").hide();
        });
```

There seem to be an issue with hiding the loading icon. (I guess)

**Comment by basuarijit** [comment] 2016-04-20 09:10
Is there any workaround for Windows?

**Comment by titospain** [comment] 2016-04-20 10:29
Thanks jacob, works like a charm!

**Comment by frank220** [comment] 2016-04-20 17:20
Same problem - any timeline on fix for windows?

**Comment by hermwong** [comment] 2016-04-20 17:56
I think the problem is that the consecutive `setTimeout` methods are causing a conflict with each other here: https://github.com/phonegap/phonegap-app-desktop/blob/master/www/js/local-storage.js#L68-L69

Based on this [stackoverflow](http://stackoverflow.com/questions/315078/how-do-you-handle-multiple-instances-of-settimeout/315133#315133) comment, it looks like I need to use `clearTimeout`.

So the code would change to something like this:

```
        var removeMissingProjectsTimeout = setTimeout(removeMissingProjects, 1000);
        clearTimeout(removeMissingProjectsTimeout);
        var hideLoaderTimeout = setTimeout(hideLoader, 1100);
        clearTimeout(hideLoaderTimeout);
```

I can easily make the change, but since I'm not able to reproduce this issue on my OSX workstation & my Win 10 VM, I'll need some volunteers to confirm if this will fix the issue.

**Comment by hermwong** [comment] 2016-04-20 21:43
Tried out the above code with the `clearTimeout` function. This seemed to cause the Desktop app to get stuck on the loading screen on my workstation.

The other solution was to move the call to the `hideLoader` method so that it would be invoked within the `removeMissingProjects` method. This change worked for me, but I still need someone that can reproduce the stuck on loading screen error to volunteer their time to test this the change.

**Comment by maxspears** [comment] 2016-04-20 22:19
Hey Guys!! I am also facing the same issue. Using windows 8.1.
I have tried all the recommendations you have posted, still no luck.

I hope phonegap support will fix this soon :(

**Comment by hermwong** [comment] 2016-04-20 22:21
I've built a test version of PhoneGap Desktop 0.3.0 with the mentioned in the above comment.

OSX users can [download](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-mac.zip) and then unzip the package and try to run `PhoneGap-0.3.0-loading-fix`.

Windows users can [download](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-win32.zip) and then unzip the package and run `PhoneGap-0.3.0-loading-fix.exe`.

Let me know if these changes resolve the issue for you. Thanks for your patience.

**Comment by maxspears** [comment] 2016-04-20 22:25
Tried the PhoneGap-0.3.0-loading-fix.exe, no luck :(

Same issue, using windows 8.1.

**Comment by hermwong** [comment] 2016-04-20 22:36
Thanks @maxspears. Can you ping me on [twitter](https://twitter.com/hermwong).

**Comment by maxspears** [comment] 2016-04-20 22:42
@hermwong I don't use twitter :(

**Comment by raysango** [comment] 2016-04-20 22:48
@hermwong thanks this package works fine

**Comment by hermwong** [comment] 2016-04-20 22:48
@maxspears I have one more potential fix that I'd like to try, would you be willing to test it for me?

**Comment by hermwong** [comment] 2016-04-20 22:49
@raysango which version did you try (OSX or Windows)?

**Comment by maxspears** [comment] 2016-04-20 22:50
@hermwong Sure, send that when you have it.

**Comment by raysango** [comment] 2016-04-20 22:51
OSX v0.3.0 "PhoneGap-0.3.0-loading-fix"

**Comment by hermwong** [comment] 2016-04-20 23:05
@maxspears, could you try `PhoneGap-Desktop-0.3.0-loading-fix-2-win32`.

@raysango, would you be willing to test `PhoneGap-Desktop-0.3.0-loading-fix-2-mac`.

**Comment by maxspears** [comment] 2016-04-20 23:06
@hermwong Link please.

**Comment by hermwong** [comment] 2016-04-20 23:07
@maxspears [here you go](https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-2-win32.zip).

**Comment by maxspears** [comment] 2016-04-20 23:09
Works for me, i got past the loading screen :)

**Comment by hermwong** [comment] 2016-04-20 23:10
@maxspears Thanks for you help! I'll likely need to patch the Desktop App to 0.3.1 with this fix.

**Comment by maxspears** [comment] 2016-04-20 23:11
Yupp!! And thanks for your help too, i am just starting with Phonegap so this was a huge step for me.

**Comment by hermwong** [comment] 2016-04-20 23:20
I've made a fix for this issue but I need someone to verify the fix for me on OSX and Windows since I'm not able to reproduce this issue on my OSX workstation & Windows VM.
 
OSX: https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-lo ading-fix-2-mac.zip
 
Windows: https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-lo ading-fix-2-win32.zip
 
Please let me know if this change works for you.

**Comment by purplecabbage** [comment] 2016-04-20 23:26
Links are broken!
OSX: 
https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-2-mac.zip
 
Windows: https://github.com/phonegap/phonegap-app-desktop/releases/download/0.3.0/PhoneGap-0.3.0-loading-fix-2-win32.zip

**Comment by hermwong** [comment] 2016-04-20 23:28
@purplecabbage thanks! Fixed it in my comment.

**Comment by frank220** [comment] 2016-04-21 08:16
Great job -- all working for me on windows 7 and 10

**Comment by hermwong** [comment] 2016-04-21 20:45
I'll be releasing new installers (PhoneGap Desktop 0.3.1) for OSX & Windows that contain the fix for this issue.

**Closed** 2016-04-21 20:44 UTC
Labels: bug, user support

**Comment by royyin224** [comment] 2016-05-09 08:28
I installed the PhoneGap Desktop 0.3.1 a week ago and it was working for my first test project. After that I started to build a more serious project using WebPack & Angular2 then the PhoneGap Desktop started to stuck at loading screen, I tried to reinstall it using the 0.3.1 installer or the zip version, nothing helped, even tried to copy the PhoneGap installation folder to a FAT32 USB drive and copy it back to remove the NTFS streams, but no luck too, is there anything else that I can try?

- PhoneGap Desktop version / PhoneGap CLI version? **0.3.1**
- PhoneGap Mobile App version? **1.6.3**
- Mobile devices & Mobile OS version? **HTC Desire 728 dual sim, Android 5.1**
- Computer OS version? **Windows 7 Premium 64 bit**
- network type (home/corporate)? **home**
- is your network using a proxy? **no**
- computer / network security (firewall / anti-virus / disk encryption)? **Windows built-in firewall/Avast 11.2.2262/no**
- are you using VMs on your computer? **no**
- do you have multiple network adapters (or virtual network adapters) **no**
- are you using VPN? **no**

**Comment by hermwong** [comment] 2016-05-09 21:31
@royyin224, based on the info you have provided I don't see any of the common issues that might cause the PhoneGap Desktop to get stuck on the loading screen.

I would suggest trying with your firewall and AV software disabled or configure them to allow PhoneGap Desktop to make external requests.

If the above suggestion doesn't work. 

Can you try deleting the localStorage used by PhoneGap Desktop. This will remove your project from PhoneGap Desktop's cache, but will not remove your project from your computer.

1. make sure you have closed PhoneGap Desktop
1. delete the localStorage at the locations below.
  - On Mac: `~/Library/Application Support/PhoneGap/Local Storage`
  - On Windows: `C:\Users\<Windows User Name>\AppData\Roaming\PhoneGap\Local Storage`
1. restart PhoneGap Desktop

**Comment by royyin224** [comment] 2016-05-10 02:16
@hermwong Thanks! By deleting the localStorage, solved the loading screen problem. Out of curiosity, what could be the cause? Is it the project's structure or its size (around 120MB)? Just to make sure I'm doing the right thing.

**Comment by hermwong** [comment] 2016-05-10 18:01
@royyin224 I'm not exactly sure what the root cause of the issue. I had a hunch that it might be something to do with your project structure that was causing a conflict with the PhoneGap Desktop.

It might be the size of the project or perhaps there might be some type of conflict with Electron trying to load a project that uses webpack or even angular 2. I haven't spent too much time testing the PhoneGap Desktop loading projects that use various libraries & frameworks; for most of my testing I've used the basic `hello world` project.

**Comment by royyin224** [comment] 2016-05-11 03:45
@hermwong Thanks :), I'll keep trying different combinations to see which combination caused the crash, I'll report back here if I find anything.

**Comment by kdoonboli** [comment] 2017-01-28 18:00
Had the same issue. So I just uninstalled the app.
Before installing it again, make sure you are NOT connected to a VPN or intranet network. Have a direct internet connection. Then run the install file as administrator. 
It works for me now. Even when I'm connected to VPN.
Originally I ran the install file on VPN, and didn't run as admin.

**Comment by jferjo** [comment] 2017-07-13 18:35
kdoonboli, this work for me. I was connected to my work network and internet, install and don't work. Then i follow you steps and work perfectly. Thanks!

**Comment by knurmi** [comment] 2017-08-15 02:32
I had this issue when I installed on Windows, but my issue came from not realizing that the installer required an internet connection. Running the post install batch file as admin with an internet connection fixed it for me.

**Comment by africanu123** [comment] 2020-03-23 18:25
For me the only version that works is PhoneGap-0.3.0-loading-fix-2-win32.zip. I have tried all the solutions provided in the comments and none of them work for me.

**Comment by Hackman777** [comment] 2020-04-01 20:56
I'm experiencing the same problem while trying to get version 0.4.5 installed on a Windows 10 system. I've uninstalled/reinstalled after disabled Windows Firewall and also tried deleting the local storage as mentioned above but it still just spins when I click on the desktop app.

Should I attempt the fix listed above for version 0.3.0 or is that fix scoped strictly to that version?

**Comment by purplecabbage** [comment] 2020-04-01 21:04
@Hackman777 You should probably move to using the Apache Cordova tooling.  This issue is 4 years old, and the phonegap desktop app has not seen development in a long long time.

**Comment by Moogamouth** [comment] 2020-09-04 03:32
I finally have a solution. Just take this:
[npm.zip](https://github.com/phonegap/phonegap-app-desktop/files/5172496/npm.zip)
Then go to PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin. There should be a file also called npm.zip in this folder. Replace it with the one I gave here. Then run the command prompt as admin, and then run `cd C:\Program Files (x86)\Adobe\PhoneGap\PhoneGap Desktop\resources\app.asar.unpacked\bin` and then `postInstall`. Wait for it to be done, and then that's it. Phonegap should work.

**Comment by Moogamouth** [comment] 2020-09-04 03:34
You probably don't care anymore cause it's been 4 years, but, if anyone wants this.
