### ISSUE TITLE
getaddrinfo EAI_AGAIN error on phonegap desktop application.

### ISSUE THREAD

**Issue by Defaultacc9** [phonegap/phonegap-app-desktop#516] opened 2015-12-22 06:04 UTC
I am trying to use Phonegap Desktop app on company network but its giving "getaddrinfo EAI_AGAIN" error. What could be the reason for this error and is there any solution for it??

Thanks in advance

**Comment by hermwong** [comment] 2015-12-22 17:36
Looks like this is a duplicate of #511.

**Comment by hermwong** [comment] 2015-12-22 17:37
Closing & locking the issue. Let's keep all discussion regarding this issue in the comments of #511.

**Closed by hermwong** 2015-12-22 17:37 UTC
Labels: bug, duplicate
