### ISSUE TITLE
Critical error !!!!

### ISSUE THREAD

**Issue by iSynth** [phonegap/phonegap-app-desktop#501] opened 2015-12-05 02:32 UTC
Phonegap desktop does not transmit latest changes to browser (autoupdate/autoreload does not work) for browser platform like for ios or android. I have to constantly press CTRL+C and write to console "phonegap run browser" to see my changes.

**Comment by hermwong** [comment] 2015-12-05 19:17
Looks like a duplicate of #453.

Closing & locking this thread so that we can keep all discussion related to this issue in #453's comments.

**Closed by hermwong** 2015-12-05 19:17 UTC
