### ISSUE TITLE
Windows bug: App crashes on build

### ISSUE THREAD

**Issue by bgstcola** [phonegap/phonegap-app-desktop#345] opened 2015-04-26 13:51 UTC
Phonegap App crashes when I build my project. I guess it has something to do with how Windows handles monitoring files that gets deleted and recreated. There are no issues when I build the project on a Mac. 

I get this error:

Uncaught node.js Error
Error: watch EPERM
    at exports._errnoException (util.js:742:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1045:26)

**Comment by hermwong** [comment] 2015-04-27 18:09
Would you be able to provide the following information:
1. Version of Windows
1. Steps to reproduce

**Comment by bgstcola** [comment] 2015-04-27 19:52
1. Windows 7 64bit.
2. Delete files ind the www folder while phonegap app is open.

**Comment by hermwong** [comment] 2015-04-27 20:04
Are you deleting the files using Windows Explorer instead of using the remove project feature in the PhoneGap Desktop App?

**Comment by bgstcola** [comment] 2015-04-28 05:54
The files get deleted when I run scripts to build the files for the project.

**Comment by hermwong** [comment] 2015-04-28 06:35
Sounds similar to issue [#300](https://github.com/phonegap/phonegap-app-desktop/issues/300) which seem to cause the PhoneGap Desktop App to crash when project files are deleted or removed without using the remove project feature in PhoneGap Desktop App.

**Comment by bgstcola** [comment] 2015-04-28 07:04
Yes I believe it's the same issue.

**Comment by hermwong** [comment] 2015-11-24 21:38
Locking thread since this is a duplicate of #300, keep all discussion of this issue in the #300 comment thread.

**Closed** 2015-11-24 21:37 UTC
Labels: duplicate, user support, windows
