### ISSUE TITLE
Unable to create project.

### ISSUE THREAD

**Issue by RupenAnjaria** [phonegap/phonegap-app-desktop#582] opened 2016-03-24 19:00 UTC
My  phonegap app shows that the server is running with IP 10.0.2.59:3000.

However, when I tried to create a project it is giving error as "connect ETIMEDOUT 192.30.252.129:443".
The setting shows IP 10.0.2.59 with port 3000.

Can someone please tell me from where exactly PhoneGap is getting the IP 192.30.252.129 with port 443?

Please see attached screenshot for the reference.

![phonegap](https://cloud.githubusercontent.com/assets/17281745/14028067/14749456-f1d1-11e5-8d9c-58daba05433f.PNG)

Setting:
![phonegap2](https://cloud.githubusercontent.com/assets/17281745/14028095/370c31a4-f1d1-11e5-9094-a7eda1e47381.PNG)

**Comment by hermwong** [comment] 2016-03-24 19:27
Could you please provide the following info?

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. computer / network security (firewall / anti-virus / disk encryption)
7. are you using VMs on your computer?
8. do you have multiple network adapters (or virtual network adapters)
9. are you using VPN?

**Comment by RupenAnjaria** [comment] 2016-03-24 19:32
Sure.Here you go.

1.     PhoneGap Desktop version / PhoneGap CLI version: **PhoneGap  Desktop version: V0.2.3**
2.     PhoneGap Mobile App version: **1.5.13**
3.     Mobile devices & Mobile OS version: **iPhone 6 s, OS 9.2.1**
4.     Computer OS version: **Windows 7**
5.     network type (home/corporate): **Corporate**
6.     computer / network security (firewall / anti-virus / disk encryption): **Firewall**
7.     are you using VMs on your computer?: **No**
8.     do you have multiple network adapters (or virtual network adapters): **No**
9.     are you using VPN? **No**

Thank you.

**Comment by RupenAnjaria** [comment] 2016-03-24 19:34
Note: Currently I am not using/connecting to mobile application. I am just trying to create a project using PhoneGap Desktop.

**Comment by hermwong** [comment] 2016-03-24 19:41
Based on the info you've provided:

I'm not sure why the settings dialog would display a different IP address than the one displayed in the error message. Do you know if your corporate network uses a proxy?

We've found that corporate networks often have security policy that prevents the PhoneGap Mobile App from downloading properly from the server being created on by the PhoneGap Desktop.

Firewalls can also cause issues to the connection between the PhoneGap Mobile App and PhoneGap Desktop App.

**Comment by RupenAnjaria** [comment] 2016-03-24 19:50
I will find out whether we are using Proxy or not. 

Meanwhile I have following questions:
1. Is it mandatory to connect Phonegap Mobile app and then to connect it to my desktop? Can't I just create a project on my desktop? - I do understand that to test I need it to connect to mobile.
2. From where PhoneGap gets the IP address to start server?

**Comment by hermwong** [comment] 2016-03-24 20:00
1. It isn't mandatory to connect the Mobile app to the Desktop if you just want to create a project.
2. The PhoneGap Desktop should create the server using the IP address of your computer.

If you type `ipconfig` in your command prompt, it should show you the IP address of your computer. The PhoneGap Desktop should use the IP address returned by `ipconfig` for the server.

**Comment by RupenAnjaria** [comment] 2016-03-24 20:39
Well, that does not seems to be the case.

If I type ipconfig, then it gives IP as 10.0.2.59 and PhoneGap is trying to
ping 192.30.252.129 with port 443 - even though I gave the port as 3000.

**Comment by hermwong** [comment] 2016-03-24 21:14
Yeah. It's strange. We haven't really had something like this reported to us. So we're trying to gather as much info as we can to trouble shoot the issue.

**Comment by hermwong** [comment] 2016-04-01 22:44
It looks like this dependency used by the `connect-phonegap` module is causing the port 443 issue that you're encountering.

https://github.com/phonegap/connect-phonegap/blob/master/lib/create.js#L205

**Comment by chrisgriffith** [comment] 2016-04-02 05:48
Just made a pull request to fix the connect-phonegap module's issues. It will now handle either the config.xml in the www folder, or up one directory. I also extended the module to support passing in a template url. It defaults to the standard hello-world.

I also tweaked the hello-world template. The spec attribute was being merged incorrectly by the app.

**Comment by hermwong** [comment] 2016-04-04 21:05
Ok I just retested this issue. I was able to get the error with the `443` port when I tried creating a project on a corporate network. However, I did not get the error when trying on my home network.

It's likely that you are receiving the port `443` error based on the security settings on your corporate network.

**Comment by tony--** [comment] 2016-04-13 20:58
I just ran into the same thing (including the IP of 192.30.252.129), also behind corporate firewall.
I thought maybe this was due to analytics, but I disabled them and it still happened.
I switched to an open network and was able to create an app.
#411 looks to be about the same thing (I just searched all issues for 192.30.252.129).

Just for the heck of it, I tried to open 192.30.252.129 in Chrome and see that it is a Github IP.
Does the app try to get retrieve something from the repo - a feed or something, maybe for update check?

**Comment by hermwong** [comment] 2016-04-13 21:04
@tony--, yes, the `connect-phonegap` dependency retrieves the `hello-world` template from Github.

**Comment by tony--** [comment] 2016-04-13 21:10
@hermwong - I just read [your comment](https://github.com/phonegap/phonegap-app-desktop/issues/582#issuecomment-204596986)
Sorry, didn't realize that you had already root-caused it!
Thanks for replying :)

**Comment by hermwong** [comment] 2016-04-13 21:16
Nothing that I can really do on the PhoneGap Desktop side of things because this is being caused by your corporate network security policy.

You could try on a non-corporate network or put in a request to allow github traffic on port 443 on your corporate network.

**Comment by kroesi** [comment] 2016-05-03 08:05
When I create a new PhoneGap project in PhoneGap-Desktop, I get the following message:
connect ETIMEDOUT 192.30.252.129:443
My settings screen shows this:

![image](https://cloud.githubusercontent.com/assets/19164607/14977674/4f8dd34a-1116-11e6-8ad2-63e465243304.png)

**Comment by hermwong** [comment] 2016-05-03 19:03
@kroesi,

When I refer to "network security policy", it refers to corporate networks having security policies in place such as firewalls, proxies etc...that the PhoneGap Desktop App can not work around. In order to get around issues caused by security policies on a corporate network, the user will need to work with their IT department to allow exceptions for the PhoneGap Desktop or use PhoneGap Desktop on a non-corporate network.

Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by kampar** [comment] 2016-05-03 22:23
I've encountered same issue ... 
Seems windows firewall blocking outside connection ... when I allow phonegap.exe to connect outside (outbound connection), seems it's fixed ...

**Comment by hermwong** [comment] 2016-05-03 22:26
@kampar Yes, you need to configure you firewall to allow PhoneGap Desktop to make outbound connections or turn off your firewall when using PhoneGap Desktop.

**Comment by pkm1983** [comment] 2016-06-09 14:15
I work for a company that specialises in security so this isn't going to work for. But from what has been said - if having a corporate firewall is a requirement, phone gap doesn't work? That seems like a huge limitation?

**Comment by hermwong** [comment] 2016-06-09 22:38
@pkm1983 PhoneGap can work behind a corporate firewall if the corporate firewall is configured to allow PhoneGap and it's dependencies to connect outside.

**Comment by surajpindoria** [comment] 2017-05-02 23:32
We are no longer using GitHub to pull the templates used by create, everything is coming from npm now. Going to close this.

**Closed by surajpindoria** 2017-05-02 23:32 UTC
Labels: user support
