### ISSUE TITLE
Phonegap Desktop turns black on windows10

### ISSUE THREAD

**Issue by luc-decraene** [phonegap/phonegap-app-desktop#632] opened 2016-05-20 08:11 UTC
The desktop version on my win10 starts well, but then hides all the buttons on left and top and I just have the black screen from the middle on the end.

**Comment by hermwong** [comment] 2016-05-23 22:26
Could you provide the following information:

1. PhoneGap Desktop version / PhoneGap CLI version
2. PhoneGap Mobile App version
3. Mobile devices & Mobile OS version
4. Computer OS version
5. network type (home/corporate)
6. is your network using a proxy?
7. computer / network security (firewall / anti-virus / disk encryption)
8. are you using VMs on your computer?
9. do you have multiple network adapters (or virtual network adapters)
10. are you using VPN?

**Comment by AngelRaposo** [comment] 2016-05-26 09:32
I just had the same exact problem and I was searching for a solution.

I fixed the problem following this steps:
 - run the server from the console with `phonegap server`
 - Windows10 asked me to allow network access to a process called `EVented I/O for V8 JavaScript` -> enable it
 - Local server starts and I can access application
 - Stop serving from CLI
 - PhoneGap Desktop app works well now

I think the desktop app is getting block when the process has no access to the network and for some reason the OS is not asking about it (when running from the app).

**Comment by luc-decraene** [comment] 2016-05-27 16:00
Hi,

The command  phonegap serve  does not ask me anything. It runs normally, so
I cannot follow step 2 of your suggestion :-(
Any other idea ?

thx,
Luc

2016-05-26 11:32 GMT+02:00 Angel Raposo <notifications@github.com>:

**Comment by luc-decraene** [comment] 2016-05-27 16:14
phonegap cli version 6.2.4 - works fine
windows 10 home 1511 build 10586.318
home network
no vpn
Phonegap desktop was last version, but I cannot check because screen is black.

**Comment by hermwong** [comment] 2016-06-03 22:50
Would you be able to provide a screen shot?

**Comment by mayank1610** [comment] 2016-07-08 09:25
I am facing the same issue with desktop app. I have tried it Windows 10 and Windows 8 both. 

This is the screenshot. It's showing Blank screen after importing app. 

Note- There is no issue in app because i have tested that app after building on phonegap build.
![capture](https://cloud.githubusercontent.com/assets/20353903/16683110/c460f83a-451b-11e6-92fb-893661451634.PNG)

**Comment by mayank1610** [comment] 2016-07-08 09:25
Kindly resolve this issue asap.......

**Comment by hermwong** [comment] 2016-07-11 20:44
Duplicate of #616

**Comment by hermwong** [comment] 2016-07-11 20:44
Closing since this is a duplicate, will use #616 to track progress of this issue.

**Closed by hermwong** 2016-07-11 20:44 UTC
Labels: bug, duplicate, windows
