### ISSUE TITLE
ajax calls not working on ios app

### ISSUE THREAD

**Issue by dev201730** [phonegap/phonegap-app-desktop#848] opened 2017-08-29 11:56 UTC

**Comment by dev201730** [comment] 2017-08-29 11:57
I get the following error lines:
304 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=

**Comment by surajpindoria** [comment] 2017-08-29 18:01
Hi @dev201730,

Could you provide some example code for how you are trying to do your ajax request. I have just tested this using both `XMLHttpRequest` and jQuery and they both worked for me. Can you also fill in the information below so that we can help you to debug this further.

1. PhoneGap Desktop version / PhoneGap CLI version
1. PhoneGap Mobile App version
1. Mobile devices & Mobile OS version
1. Computer OS version
1. network type (home/corporate)
1. is your network using a proxy?
1. computer / network security (firewall / anti-virus / disk encryption)
1. are you using VMs on your computer?
1. do you have multiple network adapters (or virtual network adapters)
1. are you using VPN?

**Comment by dev201730** [comment] 2017-08-29 18:59
1. phonegap desktop version: V0.4.5
2. phonegap mobile app version 1.7.10
3. iphone SE , os 10.3.3
4. computer os version: mac OSX YOSEMITE 10.10.5
5. home network
6. no proxy
7. idk about that
8. not when i am working with phonegap
9. no
10. no i am not using a vpn

So i am doing my ajaxCalls in the following directory  appname/www/ajaxCalls/
the ajaxUrl link: 'http://localhost:8888/appname/ajaxCalls/'
i have done this through the command line: phonegap run ios   AND  phonegap run android
and the opened the phonegap dev app on my phone,
insert the port, connection is made. Index page shows up but all the ajaxCalls fail.
I am using MAMP.

When i click on the index.html file on my computer it opens up in browser and works just fine even though i am not calling the page the following way: localhost:8888/myappname/www/index.html
so i am opening from local folder and it works. But the ajaxCalls dont work on my ios phonegap app on my iphone.


I get the following line on Server Log View:
200 /__api__/appzip
304 /socket.io/socket.io.js
200 /socket.io/?EIO=3&transport=polling&t=Luk20Sm
200 /socket.io/?EIO=3&transport=polling&t=Luk20WO&sid=DRkjdXiH9dgLSlNbAAAB

**Comment by surajpindoria** [comment] 2017-08-29 20:37
I think the issue is in your ajax URL. If you are trying to request a resource from your project the URL  will need to be relative to your current directory. Also, from the logs you posted there are no errors. Are you seeing any error messages anywhere else when you attempt to do this?

**Comment by dev201730** [comment] 2017-08-29 20:54
do you have any examples of relative URL that work. I have tried many and none works.
i also get this but i dont think it has anything to do with it:
undefined Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been modified to be: <meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' gap: ws: https://ssl.gstatic.com;style-src 'self' 'unsafe-inline' data: blob:;media-src *;img-src * 'self' data: content:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">
undefined Content Security Policy has been added: <meta http-equiv="Content-Security-Policy" content="default-src * gap: ws: https://ssl.gstatic.com;img-src * 'self' data: content:;style-src 'self' 'unsafe-inline' data: blob:;script-src * 'unsafe-inline' 'unsafe-eval' data: blob:;">

**Comment by surajpindoria** [comment] 2017-08-29 21:04
For example I tried an ajax GET request on my apps `index.html`. So I was executing from a file `project-dir/www/js/index.js` and my html is in `project-dir/www/index.html`. My ajax URL was then `../index.html`

**Comment by dev201730** [comment] 2017-08-29 21:16
Ok i will explain in detail:
i have all my files inside a Folder called MyAppName
if i get into this folder i have PLUGINS (folder), WWW(folder), HOOKS (folder), PLATFORMS(folder), config.xml (file).
If i get into the folder WWW i have index.html , JS (folder) , ajaxCalls (folder).
The ajaxCall is made from a file general.js that is inside JS(folder)  and it points to a file  getDataAjax.php that is inside ajaxCalls(folder) . The file that contains the common ajax link is called myAjaxLink.js and is found inside JS(folder).
Here the common links that i have tried but got nothing are:
1. http://localhost:8888/MyAppName/www/ajaxCalls/   (this works on browser but not on mobile phone)
2. ajaxCalls/
3. ../ajaxCalls/

**Comment by surajpindoria** [comment] 2017-08-29 21:45
If you are trying to invoke `getDataAjax.php` from within your app that will not work. PHP will not run on a cordova/phonegap app. Instead you need to host that on a web server and then make an ajax call to the server to get the data back.

**Comment by dev201730** [comment] 2017-08-29 23:17
oh i see, thank you very much for your help! :)

**Comment by hermwong** [comment] 2017-08-31 20:28
looks like issue is resolved. closing.

**Closed by hermwong** 2017-08-31 20:28 UTC
Labels: user support
