### ISSUE TITLE
listen EADDRINUSE :::3000

### ISSUE THREAD

**Issue by mrstuartlee** [phonegap/phonegap-app-desktop#536] opened 2016-01-28 11:29 UTC
Hi.

Was installing desktop Phonegap and got tonstage 3

Created app as per instructions
Didn't put anything in ID, did in somes cases, still unsuccessful.
Created app
Went to click on green arrow >
Then box at bottom shows : listen EADDRINUSE :::3000

And then can't proceed from there?????

Stuck

Anyone help? i have read a few other entries on here, but none seem to have solution?

Regards

Stuart
![screen shot 2016-01-28 at 11 27 51](https://cloud.githubusercontent.com/assets/15888115/12643163/616751f4-c5b2-11e5-99bc-98372c2297eb.png)

**Comment by hermwong** [comment] 2016-01-28 16:52
Have you tried changing the port number?

**Comment by buzcajun** [comment] 2016-02-03 20:32
I am having the same issue. I get an ERROR! then I get a DOWNLOAD ERROR!

I had it working the other day, but when I tried this morning I kept getting errors. I tried changing the port number to 4000, 2000, and even 3020. I quit and restarted twice.

**Comment by hermwong** [comment] 2016-02-10 01:03
If you have AV / firewall or on a corporate network it could cause download error because of network security settings.

**Comment by hermwong** [comment] 2016-02-10 20:12
Duplicate of #532. Locking this issue to keep all discussion centralized in #532.

**Closed by hermwong** 2016-02-10 20:13 UTC
Labels: bug
