### ISSUE TITLE
PhoneGap Desktop doesn't perform auto-reload for updates

### ISSUE THREAD

**Issue by ShmuDesign** [phonegap/phonegap-app-desktop#453] opened 2015-10-10 09:37 UTC
Hello,

Config : MacOS Yosemite and IOS 9.0.2 / dev on sublime text 2

Before the update, there is no problem with the refresh on the app, but now refresh don't work !
I tried to reinstall all components .... but nothing change.

In the server log i can see the process, "File changed".

If you have an idea !

Thanks in advance and sorry for my english.

Shmu

**Comment by hermwong** [comment] 2015-10-16 17:33
I'm not able to reproduce your issue.

I used Mac OSX Yosemite, with PG Mobile App 1.5.6 on iOS 9.0.2 and tried using both Atom Editor & TextMate.

Are you seeing the `200 /__api__/autoreload` messages in the server log?

**Comment by ShmuDesign** [comment] 2015-10-19 16:24
Hello Hermwong, thanks for your reply.
Yes i have it and i have file changed ... automatic refresh work one time and after nothing .... I need to refresh manually or restart the app.
I'm going to try with another text editor than sublime texte to see if it's not the problem.
I come back to you.

Shmu

**Comment by Software-Design** [comment] 2015-10-24 10:10
Using OS X 10.11.1 El Capitan and iOS 9.0.2 on iPhone and iPad

- I see filechanged events in log
- I see polling requests in log
- The apps don't reload automatically

So I can confirm the issue.

**Comment by hermwong** [comment] 2015-10-28 18:56
I installed OSX 10.11.1 El Capitan on one of computer and used updated to iOS 9.1 on my iPhone 6 with PG Desktop 0.1.11 and and PG Mobile App 1.5.8.

I still wasn't able to reproduce this issue.

**Comment by Software-Design** [comment] 2015-10-31 10:30
Using  the PhoneGap Desktop App the issue occurs. When running PhoneGap from the terminal everything works fine.

**Comment by surajpindoria** [comment] 2017-05-02 21:36
There have been significant improvements to both the desktop app and the server component. I am going to close this issue, if you are still seeing this please feel free to reopen.

**Closed by surajpindoria** 2017-05-02 21:36 UTC
Labels: bug, user support
