### ISSUE TITLE
Unable to connect android device

### ISSUE THREAD

**Issue by mohandutt134** [phonegap/phonegap-app-desktop#529] opened 2016-01-21 18:50 UTC
Using Phonegap desktop app on mac and phonegap develop app on my android device.
Once the files gets extracted on the phone, it gets stuck at "Connecting to device" and on desktop app, the console shows "200/**api**/autoreload" continuously.

**Comment by hermwong** [comment] 2016-01-21 19:33
possible duplicate of #423

**Comment by mohandutt134** [comment] 2016-01-22 03:30
@hermwong i m not getting error message anywhere, its just that the phone is not connecting to device after the extraction of files

**Comment by hermwong** [comment] 2016-02-11 22:23
Do you have a firewall/AV or are you on a corporate network?

We've found that those things can sometimes prevent the zip archive from being served from the PhoneGap Desktop to the PhoneGap Mobile App.

**Comment by surajpindoria** [comment] 2017-05-02 22:51
Closing due to inactivity, please reopen if this is still an issue.

**Closed by surajpindoria** 2017-05-02 22:51 UTC
Labels: bug
