### ISSUE TITLE
Selected folder  doesn't contain config.xml file.

### ISSUE THREAD

**Issue by MaheshNaik07** [phonegap/phonegap-app-desktop#469] opened 2015-10-29 15:29 UTC
I have installed phonegap desktop app on windows 7.While creating a new project it gives  following error
"Selected folder  doesn't contain config.xml file".

Please provide a solution for this problem.

**Comment by hermwong** [comment] 2015-10-29 16:59
possible duplicate of #322

**Comment by hermwong** [comment] 2015-11-24 21:43
Closing due to lack of feedback / info from the user.

**Closed by hermwong** 2015-11-24 21:43 UTC
Labels: need user feedback / more info, user support
