### ISSUE TITLE
Server is running/offline tab missing

### ISSUE THREAD

**Issue by aman89sandhu** [phonegap/phonegap-app-desktop#650] opened 2016-07-18 17:32 UTC
![untitled](https://cloud.githubusercontent.com/assets/20522065/16924174/9726009a-4d3b-11e6-8051-61407af56c66.png)
firewall disable and no antivirus
phonegap version 0.3.3
windows 7 32 bit

**Comment by hermwong** [comment] 2016-07-18 17:48
duplicate of #649

**Closed by hermwong** 2016-07-18 17:48 UTC
Labels: bug, duplicate, windows
