### ISSUE TITLE
Phone Gap Desktop Project Creation Issue

### ISSUE THREAD

**Issue by ZubairKh** [phonegap/phonegap-app-desktop#386] opened 2015-06-25 07:05 UTC
When I try to create a new project. It gave connection ETIMEDOUT 192.30.252.31:443. I know the IP doesn't belongs to my PC but where to change this configuration? I searched a lot cannot be able to fine a solution.

**Comment by haider-ali** [comment] 2015-06-26 10:38
I am having the same issue , is there any configuration needed to done before creating a project?

**Comment by hermwong** [comment] 2015-06-26 18:01
In most cases there isn't any configuration required for creating a new project using the `PhoneGap Desktop`.

We've noticed that people that have the following setup may encounter issues when using the `PhoneGap Desktop`:

- firewall software
- av software
- disk encryption software
- connecting on a corporate network or a network behind a firewall
- multiple network adapters installed on computer

@ZubairKh, would you be able to change the port used by the `PhoneGap Desktop` to a different port? Port `443` may already be in use or be blocked.

**Comment by haider-ali** [comment] 2015-06-27 05:09
my problem is 
      connecting on a corporate network or a network behind a firewall
because when i tried it on a network without proxy it works. Thanks, but how can i set the proxy in PhoneGap Desktop app

**Comment by saadou** [comment] 2015-07-03 13:47
i'm facing the same isuue with the Proxy,is there a proxy configuration ?

**Comment by hermwong** [comment] 2015-07-07 18:06
Unfortunately, we currently do not the ability to support proxy configuration in the PhoneGap Desktop App.

It's a feature that we're currently investigating.

**Comment by hermwong** [comment] 2015-07-08 16:27
Duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/356

**Closed by hermwong** 2015-07-08 16:27 UTC
Labels: user support

**Comment by hermwong** [comment] 2015-10-06 20:45
Here is a workaround: https://github.com/phonegap/phonegap-app-desktop/issues/356#issuecomment-145995007
