### ISSUE TITLE
Server is offline and right arrow button does nothing

### ISSUE THREAD

**Issue by bobbydombrowski** [phonegap/phonegap-app-desktop#276] opened 2015-01-17 15:57 UTC
I've tried using the phonegap desktop app on 2 different macbook pros and neither successfully show a running server in the green bar. All directions say "If server doesn't start automatically, click the right arrow button to the right of your app project name," but clicking on the right arrow does nothing.

I can't find any guidance on how to resolve this.

Thanks for any help.

**Comment by hermwong** [comment] 2015-01-20 21:32
Hi @bobbydombrowski,

If you are seeing the green bar on the bottom it means the server is already started. The green bar should display the IP address of the server, something like `http://192.168.1.120:3000`.

If you have the PhoneGap Developer App downloaded onto your mobile device you can just type in the server IP address and connect to the server created by the PhoneGap Desktop App.

Your computer that has the PhoneGap Desktop App and your mobile device that has the PhoneGap Developer App need to be on the same network.

More details can be found [here](https://github.com/phonegap/phonegap-app-desktop/wiki/PhoneGap-Desktop-FAQ#phonegap-desktop-app--phonegap-developer-app).

**Comment by bobbydombrowski** [comment] 2015-01-21 01:42
I have never actually seen the green bar....I only see the grey bar with "Server is offline." The only troubleshooting steps for this is to "Click on right arrow," but my right arrows are inactive...nothing happens on click.

**Comment by hermwong** [comment] 2015-01-21 04:09
Would you be able to provide the following details for me:

1. are you using the Windows or Mac version of the PhoneGap Desktop?
1. does your computer have Internet access?
1. are you on a VPN or corporate network?
1. do you have AV or a firewall installed on your computer?

**Comment by bobbydombrowski** [comment] 2015-01-21 14:18
1. Mac
2. Yes
3. I've tried at home and at work on corporate network
4. Work computer (YES to Both) Home computer (NO to both)

Thanks

**Comment by hermwong** [comment] 2015-01-23 23:23
I'm not able to reproduce your issue and can't think of what could be causing the issue off the top of my head.

Could you post a screen shot?

Are there any other details that we could be missing in terms of computer / network configuration that could be causing the issue?

**Comment by bobbydombrowski** [comment] 2015-01-23 23:27
[image: Inline image 1]

I really don't know anything else to consider. It's just not working, but I
can use the phonegap build website.

**Comment by jcornic** [comment] 2015-01-26 13:50
It seems that I have the same problem.
"Server is offline" and the gray arrow is not clickable.

I'm with a mac (Yosemite) / WiFi...

**Comment by gaurav1992** [comment] 2015-01-26 21:03
I am getting the same problem too .

here is screen shot 

![screen shot 2015-01-27 at 2 29 59 am](https://cloud.githubusercontent.com/assets/4508926/5908349/a7c70772-a5cc-11e4-978d-52ae26425dc9.png)


@hermwong I need to short out this problem as soon as possible let me know if you guys find any solution for this yet .

Thanks

**Comment by kmengineering** [comment] 2015-02-11 18:28
anyone find a solution to this yet?  I am encountering the same issue, but on windows8.1  - server doesn't start and right arrow does nothing like screenshot posted by gaurav1992.  running phonegap as administrator and already unblocked the other files.  thanks

**Comment by hermwong** [comment] 2015-02-11 19:37
We're still trying to troubleshoot this issue.

**Comment by kmengineering** [comment] 2015-02-11 20:43
If it helps, I seem to be able to create and run a new app - but an existing app will not start the server.

**Comment by maxthinker** [comment] 2015-02-26 05:33
I have this problem too.

I just realized server does start, but very late. 

Windows 7 64bit.
Norton Firewall & AV.
Internet Access: Yes.

**Comment by zephinzer** [comment] 2015-06-17 09:01
Had the same problem but it resolved after I removed a symlink that was not working. Discovered the error after running 'phonegap serve' in the project folder.

**Comment by koushik72** [comment] 2015-12-19 17:15
![image](https://cloud.githubusercontent.com/assets/12221775/11914276/326ecd16-a6a2-11e5-9b01-7b587f959566.png)

Same problem here.
But I can't even see the server offline footer.
Please help.
Thanks.

**Comment by koushik72** [comment] 2015-12-19 17:52
Guys, I just figured it out. Just got the solution.
First run this command from the cmd line
npm install -g phonegap

Now it's working fine.
![image](https://cloud.githubusercontent.com/assets/12221775/11914434/64e0d104-a6a7-11e5-99de-cd5e9d271f8a.png)

**Comment by MMMHRB** [comment] 2016-03-07 23:41
hello every one.
i am facing a problem here. i have got two projects in my laptop.one of them is working fine in phonegap but the other has got a problem which is server is offline. i am using windows 10.
![untitled](https://cloud.githubusercontent.com/assets/17713232/13587160/1b7a9d92-e4be-11e5-9753-aa7e8461ed1d.png)

**Comment by MMMHRB** [comment] 2016-03-07 23:42
employee record project is working fine where as the above one is not. for the above project the error come up like server is offline or some times it doesnot show any error

**Comment by hermwong** [comment] 2016-03-07 23:46
Hi @MMMHRB, 

Could you list the step by step instructions on how you got the issue to appear?

Would you also be able to let us know which version of PhoneGap Desktop you are using?

**Comment by bhavikdesai94** [comment] 2016-05-05 09:38
I have same problem but i found the solution that if your project doesn't in www folder than it will not works for you so put your all the files in www folder than try to run your application it will surely works.

**Comment by emnullfuenf** [comment] 2016-05-16 15:50
I've got the same problem on OS X 10.11 with Phonegap Desktop 0.2.1 and 0.3.2.

**Comment by emnullfuenf** [comment] 2016-05-16 15:56
Solvedhere: P5.js was running and blocking the same ports.
sudo lsof -i :3000 # checks port 3000

**Comment by mingzuo** [comment] 2016-11-14 06:20
i just removed the directory <MY_PROJECT>/platforms/browser/ , then it works!

**Comment by Dmatafonov** [comment] 2017-01-25 19:08
Well, if it'd help anyone, it works for me if I choose parent directory of the www folder.
If I select ww folder, icon is displayed, but server wont start,

![image](https://cloud.githubusercontent.com/assets/8863854/22304944/5f78dc92-e342-11e6-8d9b-1fa354f477c7.png)

**Comment by surajpindoria** [comment] 2017-04-28 21:33
This is an older issue and we have released a number of fixes that could potentially help with some of your issues. Going to close this out, if you are still seeing this please feel free to reopen.

**Comment by 100jan** [comment] 2017-05-02 16:09
Having the same issue here.
Windows 8.1 Pro. No firewall.
![phonegap-desktop-error](https://cloud.githubusercontent.com/assets/1894209/25627253/4220d4bc-2f62-11e7-824c-fafb3dad32b6.jpg)

**Comment by surajpindoria** [comment] 2017-05-02 18:18
Which version of the app are you using @100jan?

**Comment by 100jan** [comment] 2017-05-03 00:27
Version is 0.4.4

**Comment by surajpindoria** [comment] 2017-05-03 01:52
Did you use the installer or the zip file?

**Comment by 100jan** [comment] 2017-05-03 14:13
Windows installer.

**Comment by surajpindoria** [comment] 2017-05-03 17:29
We had some issues with the original installer we published on Friday, I fixed and put up some new ones on Monday. Not sure if you used the old one, but if you did could you try the new installer. Also does this also occur when you create a new project?

**Comment by 100jan** [comment] 2017-05-04 19:02
When I create new project it works. 
I tried new installer now, same result.

**Comment by surajpindoria** [comment] 2017-05-04 20:19
My guess then is that there is something in your project that is causing the serve to fail behind the scenes. What is the file structure like in your project?

**Comment by StijnK** [comment] 2017-08-10 14:52
just open you main map that you select in phonegap, IN THAT FOLDER create a www folder, and put all files in there. so you got:
projectmap/www/index.html
this worked for me

**Comment by knurmi** [comment] 2017-08-15 02:44
I'm using the most recent, and I had the grey arrow issue too. The solution I've come to is create a new app.

I created a version of the Hello World template app, it started the server, then I clicked the arrow on my existing project and it switched it over.

**Comment by hutch365** [comment] 2017-08-15 08:59
Same as Knurmi,  worked for me thanks.

**Comment by aledc7** [comment] 2018-02-02 21:52
The Solution is simply, jusst create a new project.
  Just click on + button and "create New Phonegap proyect" .    then, choose "hello world"  or ahother you want.     This work for me.  i am  mac sierra


Saludos desde Argentina

**Comment by DoneDevelop** [comment] 2018-04-11 08:32
![bitmoji](https://render.bitstrips.com/v2/cpanel/204d8f0d-50e5-4db5-a810-f6525a68dc39-e5f5d06a-bb40-4f30-9271-d78c678361dc-v1.png?transparent=1&palette=1&width=246) I have the same issue

**Comment by Mad-Chemist** [comment] 2018-09-01 15:18
Same issue on Mac.  Can't even create a "New Blank App" from the Phonegap application.  I could create the "Hello World" example and have the server run for that, but my app never connects.

**Closed** 2019-03-28 16:08 UTC
Labels: question, user support, wontfix
