### ISSUE TITLE
EADDRINUSE:3000, firefall off, no antivirus blocking, still i am getting the error, getting multiple ip address, not able to connect through mobile.. please help... 

### ISSUE THREAD

**Issue by ramkumarcan** [phonegap/phonegap-app-desktop#548] opened 2016-02-20 12:18 UTC

**Comment by hermwong** [comment] 2016-02-22 20:48
Duplicate of #532. Fix will be included in PhoneGap Desktop 0.2.2.

**Closed by hermwong** 2016-02-22 20:48 UTC
