### ISSUE TITLE
Phonegap Desktop 0.2.1 Won't auto reload windows

### ISSUE THREAD

**Issue by noveweb** [phonegap/phonegap-app-desktop#517] opened 2015-12-23 18:35 UTC
Auto realod/refresh after update html/js/css does not work.

**Comment by hermwong** [comment] 2015-12-24 04:34
Looks like a duplicate of #453. Closing & locking this issue, so that we can keep all discussion in the comment thread of #453.

**Closed by hermwong** 2015-12-24 04:34 UTC
Labels: bug, duplicate
