### ISSUE TITLE
unable to download archive from server

### ISSUE THREAD

**Issue by mahesh8488** [phonegap/phonegap-app-desktop#410] opened 2015-07-29 22:15 UTC
I am using v0.1.8 phonegap desktop app. I am trying to connect Windows Phone 8.1.

**Comment by hermwong** [comment] 2015-08-03 20:27
Duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/396

**Closed by hermwong** 2015-08-03 20:27 UTC
