### ISSUE TITLE
Unable to Properly connect to the server

### ISSUE THREAD

**Issue by sgszha17** [phonegap/phonegap-app-desktop#456] opened 2015-10-14 12:36 UTC
I have:
PhoneGap Developer App (Windows 10): v0.1.11
and there is no firework problem.
Using Android 5.0.2 phone.
But it still cannot download the archive. 
And I am sure, the phone and laptop were using same network, and the address is correct.

**Comment by msawant** [comment] 2015-10-14 15:09
O have the same problem. Unable to download archive from the server, unable to properly connect to the server

phonegap --version
5.3.6

desktop app version 0.1.11

BTW I also get the same error with 0.1.7

**Comment by hermwong** [comment] 2015-10-14 15:32
Are you using a virtual machine or do you have multiple virtual network adapters on your computer?

If so you could try [disabling](https://github.com/phonegap/phonegap-app-desktop/issues/356#issuecomment-145995007) the virtual network adapters.

**Comment by msawant** [comment] 2015-10-14 15:40
No virtual machines, and no multiple virtual network adapters

**Comment by sgszha17** [comment] 2015-10-14 15:42
Yes, I got a VMware Workstation. But, still cannot download when I disabling...

**Comment by hermwong** [comment] 2015-10-14 15:43
Looks like a duplicate of #396, we are still investigating this issue.

Locking this thread so that we can keep all discussion regarding this issue in #396.

**Closed** 2015-10-14 15:43 UTC
Labels: user support
