### ISSUE TITLE
Latest version of Phonegap desktop software is not working in windows 10

### ISSUE THREAD

**Issue by kalaiprakash93** [phonegap/phonegap-app-desktop#916] opened 2020-02-12 05:07 UTC
### Expected Behaviour:
 Not working in  windows 10. its keep on loading after installed and opened. I am currently using 0.3.0.This version also makes me trouble.In this version it keep on stopping while saving code changes.

### Actual Behaviour:
I am expecting better software for Phonegap development.

#### Error messages
Keep on loading - v0.4.5
stopped continously - v0.3.0

**Comment by solWEB** [comment] 2020-02-19 03:15
I have the same problem :(

**Comment by chrisgriffith** [comment] 2020-02-26 22:48
Duplicate of #913 
See comment: https://github.com/phonegap/phonegap-app-desktop/issues/913#issuecomment-571156198 for a possible local fix

**Comment by zju1** [comment] 2020-05-09 10:20
How to fix this?

**Comment by chrisgriffith** [comment] 2020-05-09 21:03
See the comment I left above. Also, this software is no longer maintained. Please use the CLI directly.

**Closed** 2020-12-19 08:00 UTC
Labels: wontfix
