### ISSUE TITLE
PG Desktop Autoreload Doesn't work....

### ISSUE THREAD

**Issue by phonicmouse** [phonegap/phonegap-app-desktop#520] opened 2016-01-04 23:51 UTC
After i changed the index.html adding a custom css file, on the phonegap dev app the changes doesn't refresh..
(sorry for the bad english, i'm italian)

**Comment by hermwong** [comment] 2016-01-04 23:59
Duplicate of #453.

**Closed by hermwong** 2016-01-04 23:59 UTC
Labels: bug, duplicate
