### ISSUE TITLE
Add existing project not working or element from list is invisible (?).

### ISSUE THREAD

**Issue by ErniW** [phonegap/phonegap-app-desktop#505] opened 2015-12-09 02:29 UTC
Hi,
Sometimes when I use the app the selected folder shows on list but sometimes(mostly) not. I was thinking about relation between config file but that's not it.

What is strange - if the server is running, even without clicking to run the server with the one folder which loads (the run button is inactive), the "invisible" app shows on mobile app and server is working.

Is the element not displayed on the list?

This issue makes the app unusable from my point of view.

I'm using windows 10.

**Comment by OutsourcedGuru** [comment] 2016-02-11 01:09
I think this is the same issue that I'm seeing.  I just re-installed, hoping to make this problem go away but it persists.

OS X El Capitan
PhoneGap Desktop app v0.2.1

I have two projects which have been working fine.  In both cases I selected the PhoneGap Desktop app's "Open PhoneGap Existing App..." feature.  The PhoneGap Desktop app behaves exactly as you would hope, tracking the OFF/ON state and showing the placeholder for the app with its name and icon.

For the next project I created it _inside_ the PhoneGap Desktop app with "Create New PhoneGap App..."  Now, for this project:

1) it does not show a placeholder for the app but it does indicate that the server is listening and yes, the app is being served (as confirmed using a browser to the indicated port)
2) since it has no placeholder there isn't a way of deleting the project
3) since the project can't be deleted it always runs on startup and further, it can't be stopped
4) upon deleting the PhoneGap Desktop app and re-installing it, the last project settings are still there and I'm now stuck

Where is the project list?  Alternately, how can I purge the project list?

I tried temporarily moving ~/Library/Preferences/com.electron.phonegap.plist and likewise com.w-builder.phonegap.plist and the app still remembers the project settings.

**Comment by hermwong** [comment] 2016-02-11 01:40
The PhoneGap Desktop cache / local storage can be reset.

Following the instructions here: https://github.com/phonegap/phonegap-app-desktop/issues/519#issuecomment-168791674

**Comment by OutsourcedGuru** [comment] 2016-02-11 03:33
Eureka!  @hermwong Well done.  That technique at least allowed me to repeatedly purge the project database to troubleshoot.  Found a really cool bug for you.

PhoneGap Desktop app -> Create New App ->
  (Produces a config.xml in line:
  <preference name="exit-on-suspend" value=**“false”**/>
...which should be instead:
  <preference name="exit-on-suspend" value="false"/>

Trust me, this is subtle.  See the double quotes around the word false in the first instance?  Those are actually the forward-leaning version of the double quote rather than the expect one (0x22).  This is enough to blow out everything and to cause the LocalStorage mechanism to go completely crazy.  I don't know where it is, but somewhere within the PhoneGap Desktop app itself when you attempt to create a new app there's code that creates the new config.xml file.  That's your culprit, the part where it tries to create that line.

Good luck!

**Comment by theogray** [comment] 2016-02-29 15:51
I have been experiencing this as well for some time since starting on a new app and this afternoon have managed to finally get the second app added and displayed.

The problem in my case appears to be resolved by removing the `?xml` line at the beginning of the file i.e. `<?xml version="1.0" encoding="UTF-8" ?>` (originally added as per [Configuring The Basics](http://docs.build.phonegap.com/en_US/configuring_basics.md.html)).

My original app has this line in and still works fine in PG Desktop though, so is there some sort of validation issue that could be causing this strange behaviour? My original app still has as many of the old tags as PG Build will let me get away with, whereas for this second app I've cleaned up config.xml and used the non-`gap:` versions throughout.

Other things tried:
- Adding the `?xml` line back in and updating `widget version` while PG Desktop open: Server Log shows file has changed but new version not displayed. Server still running and project served to mobile app as normal though. Remove `?xml` line and save again, new version now displayed in PG Desktop.
- Adding the `?xml` line back in while PG Desktop closed: On restart of PG Desktop, the project no longer displays and server doesn't start. Removing the line and restarting PG Desktop makes the project reappear and work fine.

**Comment by zhang024** [comment] 2016-12-16 05:17
@theogray thank you, saved me much time, after I removed <?xml version="1.0" encoding="UTF-8" ?> line from config.xml, PG works well now.

**Comment by solbergw** [comment] 2017-04-15 00:20
I had attempted removing `<?xml version="1.0" encoding="UTF-8" ?>` as well which resolved the issue, but I was not satisfied.  I opened the config file in the Notepad++ editor and changed the encoding to UTF-8 and kept the xml tag in the document.  This resolved the actual issue which was the actual encoding of the document.

**Comment by surajpindoria** [comment] 2017-05-02 22:15
This seems to be resolved, going to close this off.

**Closed by surajpindoria** 2017-05-02 22:15 UTC
Labels: bug, user support, windows
