### ISSUE TITLE
unable to download archive from the server.unable to properly connect to the server.

### ISSUE THREAD

**Issue by gawalirajat** [phonegap/phonegap-app-desktop#450] opened 2015-10-02 17:20 UTC
when im trying to connect to the server address provided by the desktop app my mob app is constantly showing the message.....unable to download archive from the server.unable to properly connect to the server.......!!!
i had reinstalled both the apps several times but its not showing any progress...
PLZ HELP ME.....!!!!!

**Comment by hermwong** [comment] 2015-10-06 18:51
Could you provide more information regarding your system configuration?

**Comment by hermwong** [comment] 2015-10-06 18:52
Duplicate of: #396

**Comment by gawalirajat** [comment] 2015-10-06 18:54
I have got windows 10 running on my PC.4 GB of ram,Intel i3 processor.

**Comment by hermwong** [comment] 2015-10-06 18:56
Closing and locking this issue. Let's keep all discussion regarding this bug in #396.

**Closed by hermwong** 2015-10-06 18:56 UTC
Labels: user support
