### ISSUE TITLE
You have been opted out of telemetry

### ISSUE THREAD

**Issue by classic12** [phonegap/phonegap-app-desktop#825] opened 2017-07-18 13:32 UTC
### Expected Behaviour

I have just installed the desktop version on a Mac and get this error while trying to create a hello world app.

#### Error messages

You have been opted out of telemetry. To change this, run: cordova telemetry on.
Creating a new cordova project.
Using cordova-fetch for phonegap-template-hello-world@4.0.3
Error: Uncaught, unspecified "error" event. ([1m [31m Error from Cordova Fetch: Error: npm: Command failed with exit code 243 Error output:
npm WARN locking Error: EACCES: permission denied, open '/Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock failed { Error: EACCES: permission denied, open '/Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock'
npm WARN locking     at Error (native)
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   syscall: 'open',
npm WARN locking   path: '/Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock' }
npm WARN enoent ENOENT: no such file or directory, open '/Users/WorkMac/.cordova/package.json'
npm WARN .cordova No description
npm WARN .cordova No repository field.
npm WARN .cordova No README data
npm WARN .cordova No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Applications/PhoneGap.app/Contents/Resources/app/bin/node" "/Applications/PhoneGap.app/Contents/Resources/app/node_modules/npm/bin/npm-cli.js" "install" "phonegap-template-hello-world@4.0.3"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path /Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open '/Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, open '/Users/WorkMac/.npm/_locks/staging-0130e0b394a7fc27.lock'
npm ERR!     at Error (native)
npm ERR!   errno: -13,

**Comment by surajpindoria** [comment] 2017-07-18 18:23
Hi @classic12,

You can ignore the message about telemetry, that is a different issue that I have already fixed for the next release. The bigger issue here is that cordova-fetch is failing with npm EACCES issues. Can you try follow the instructions in this guide and let me know if it resolves your issue.

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by hermwong** [comment] 2017-07-18 21:25
duplicate of #814

**Comment by Muneebwasikhan** [comment] 2018-08-21 06:39
turn on the telemetry run
$ cordova telemetry on

**Closed** 2019-03-17 08:20 UTC
Labels: duplicate, user support, wontfix
