### ISSUE TITLE
Phonegap App not loading

### ISSUE THREAD

**Issue by sticcino** [phonegap/phonegap-app-desktop#915] opened 2020-01-18 17:26 UTC
### PhoneGap Desktop version
LATEST
### PhoneGap Mobile App version
LATEST
### Mobile devices & Mobile OS version
N/A
### Computer OS version
WINDOWS 10 64-BIT
### Network Type (home/corporate)
HOME
### Is your network using a proxy?
NO
### Computer / Network security (firewall / anti-virus / disk encryption)
WINDOWS SECURITY
### Are you using VMs on your computer?
NO
### Do you have multiple network adapters (or virtual network adapters)?
NO
### Are you using VPN?
NO
### Expected Behaviour
SHOULD RUN
### Actual Behaviour
HANGS ON STARTUP 
### Steps to Reproduce 
install
#### Error messages
none

re-installed dozens of times, tried all "supposed" fixes posted, still same issue, also tried the  .45 beta no go. run as admin, do postinstall.bat -- nothing

typical adobe garbage, once they get their hands on something.

**Comment by asadmalik** [comment] 2020-01-27 09:56
Same here. :( 👎

**Comment by gtmsingh** [comment] 2020-01-28 17:46
+1

**Comment by gtmsingh** [comment] 2020-01-28 18:11
Issue is resolved in discussion of this: #913 

Duplicate of #913

**Closed** 2020-08-23 20:21 UTC
Labels: wontfix
