### ISSUE TITLE
Issue in Sync'ing from Macbook App and iPhone

### ISSUE THREAD

**Issue by samirsyed29** [phonegap/phonegap-app-desktop#557] opened 2016-02-25 05:10 UTC
I just installed PhoneGap as I am looking to build Mobile Apps using frameworks like PhoneGap or Ionic etc.

I looked at Ionic and found its compiling process pretty easy and no trouble.

I wanted to try PhoneGap and see how it works. I downloaded the desktop app for Mac and then the app for iPhone in my iPhone 6S and i follow the steps which are on the website.

I put in the Correct server address in the Phone's App and hit Connect and BOOM, the Desktop App goes blank.

I checked the log and the blank screen happens right after 404/_api_/appzip is logged.

I know this is a duplicate but i downloaded the apps just today itself and it has this problem?

I thought the issues were solved and were fixed but looks like they aren't.

I am dissapointed.

**Comment by moelelo** [comment] 2016-02-25 15:46
Same for me!

**Comment by hermwong** [comment] 2016-02-25 20:00
Thanks for reporting this issue. We've been able to find the root cause of the issue and will be releasing a fix very soon.

Duplicate of #553.

**Comment by samirsyed29** [comment] 2016-02-25 20:02
Thank you so much. I was almost moving away from PhoneGap to Ionic. But any
approximate date of when you will be releasing the update ?

On Thu, Feb 25, 2016 at 12:00 PM, Herm Wong <notifications@github.com>
wrote:

> Thanks for reporting this issue. We've been able to find the root cause of
> the issue and will be releasing a fix very soon.
>
> Duplicate of #553
> <https://github.com/phonegap/phonegap-app-desktop/issues/553>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-188953582>
> .
>



-- 
*Samir Syed*

**Comment by hermwong** [comment] 2016-02-25 20:04
Should be released later today, I'll update this issue when I push the patch up.

**Comment by samirsyed29** [comment] 2016-02-25 20:54
Sure! Thank you

On Thursday, February 25, 2016, Herm Wong <notifications@github.com> wrote:

> Should be released later today, I'll update this issue when I push the
> patch up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-188956398>
> .
>


-- 
*Samir Syed*

**Comment by hermwong** [comment] 2016-02-25 20:55
For the time being I suggest that you use [PhoneGap Desktop 0.2.1](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.2.1)

**Comment by samirsyed29** [comment] 2016-02-25 20:56
Ok i'll try it right now

On Thursday, February 25, 2016, Herm Wong <notifications@github.com> wrote:

> For the time being I suggest that you use PhoneGap Desktop 0.2.1
> <https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.2.1>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-188981940>
> .
>


-- 
*Samir Syed*

**Comment by hermwong** [comment] 2016-02-25 21:02
This is what we've found [so far](https://github.com/phonegap/phonegap-app-desktop/issues/553#issuecomment-188983077).

**Comment by samirsyed29** [comment] 2016-02-25 21:19
PhoneGap 0.2.1 works perfect on windows. Will try it on my macbook and will
update here

On Thu, Feb 25, 2016 at 1:02 PM, Herm Wong <notifications@github.com> wrote:

> This is what we've found so far
> <https://github.com/phonegap/phonegap-app-desktop/issues/553#issuecomment-188983077>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-188986146>
> .
>



-- 
*Samir Syed*

**Comment by hermwong** [comment] 2016-02-25 22:42
Hi @samirsyed29 can you try out the preview build of [PhoneGap Desktop 0.2.3](https://github.com/phonegap/phonegap-app-desktop/releases/tag/untagged-578bec901bcbac287e01) and let me know if it works for you?

**Comment by samirsyed29** [comment] 2016-02-25 22:44
Sure, i'll do that right now.

On Thu, Feb 25, 2016 at 2:43 PM, Herm Wong <notifications@github.com> wrote:

> Hi @samirsyed29 <https://github.com/samirsyed29> can you try out the
> preview build of PhoneGap Desktop 0.2.3
> <https://github.com/phonegap/phonegap-app-desktop/releases/tag/untagged-578bec901bcbac287e01>
> and let me know if it works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-189016684>
> .
>



-- 
*Samir Syed*

**Comment by samirsyed29** [comment] 2016-02-25 22:51
Works good now Herm. I'll try it on my macbook later, but it works good in
windows.

On Thu, Feb 25, 2016 at 2:43 PM, Herm Wong <notifications@github.com> wrote:

> Hi @samirsyed29 <https://github.com/samirsyed29> can you try out the
> preview build of PhoneGap Desktop 0.2.3
> <https://github.com/phonegap/phonegap-app-desktop/releases/tag/untagged-578bec901bcbac287e01>
> and let me know if it works for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#issuecomment-189016684>
> .
>



-- 
*Samir Syed*

**Comment by hermwong** [comment] 2016-02-25 22:53
Great thanks for helping out! It's much appreciated.

**Closed by hermwong** 2016-02-25 22:53 UTC
Labels: bug, duplicate

**Comment by samirsyed29** [comment] 2016-02-25 22:59
Thank you

On Thu, Feb 25, 2016 at 2:53 PM, Herm Wong <notifications@github.com> wrote:

> Closed #557 <https://github.com/phonegap/phonegap-app-desktop/issues/557>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-app-desktop/issues/557#event-566506606>
> .
>



-- 
*Samir Syed*
