### ISSUE TITLE
www folder size greater than 10MB is throwing error while downloading "unable to download archive from the server"

### ISSUE THREAD

**Issue by kumarvikash** [phonegap/phonegap-app-desktop#374] opened 2015-06-17 14:17 UTC
I am getting "unable to download archive from the server" when my www folder size is greater than 7MB.

But phonegap developer app on iPAD mini successfully connect when www folder size is less than 5 MB.

**Comment by mwbrooks** [comment] 2015-06-17 19:41
Hi @kumarvikash,

What device are you using when you down the 7MB+ app?

If possible, could you attach your application? I understand if your application is private and you cannot provide the source code.

**Comment by kumarvikash** [comment] 2015-06-18 07:01
I am using iPad mini with iOS version 8.3 
To reproduce this issue follow below steps
1) Open phonegap developer app on window 7.
2) Create a new PhoneGap project on developer app.
3) Give project name, location then save.
4) It will show green status bar in bottom saying "Server is running on http://XX.XXX.XX.XX:3000"
5) Then go to the folder location where new project is created.
6) Add any files to make www folder size greater than 7 MB. You can also add photos(Just for testing)
7) Then go to iPad mini. Hit your IP:3000. That's it. You will get download error.

Just to verify
8) Go to the folder again and just remove the pics which you have added in www folder.
9) Run again iPad mini. You will see its successfully connecting.

**Comment by hermwong** [comment] 2015-06-19 22:05
Related to: https://github.com/phonegap/phonegap-app-desktop/issues/360

**Comment by surajpindoria** [comment] 2017-05-02 18:30
We have made some significant improvements to the underlying server component and I am not able to reproduce this with an app of 30mb. Going to close this, please reopen if you are still seeing this.

**Closed by surajpindoria** 2017-05-02 18:30 UTC
Labels: user support
