### ISSUE TITLE
Connection problem with PhoneGap Developer App

### ISSUE THREAD

**Issue by hayg** [phonegap/phonegap-app-desktop#566] opened 2016-03-01 03:43 UTC
I'm trying to connect my PC which has Windows 10 with my iPhone 6
But on the phone screen I just see an ERROR like this "unable to download archive from this server" and "Please enter a valid url to connect to." I've checked the IP address for thousand times but nothing changed
PLEASE HELP ME SOS!!!!! 
@PhoneGap Developer Mobile App

**Comment by jcesarmobile** [comment] 2016-03-01 08:58
Maybe you have a problem with your internet connection as you opened the same issue 4 times

https://github.com/phonegap/phonegap-app-desktop/issues/563
https://github.com/phonegap/phonegap-app-desktop/issues/564
https://github.com/phonegap/phonegap-app-desktop/issues/565

Can you close them?

Are the PC with Windows 10 and the iPhone 6 on the same wifi network? Are you under a proxy?

**Comment by hermwong** [comment] 2016-03-01 21:24
Are you behind a firewall, corporate network, VPN?

Do you have AV software?

Are you using PhoneGap CLI or PhoneGap Desktop to serve to the PhoneGap Developer App?

What version are you using for:
1. PhoneGap CLI (or PhoneGap Desktop)
1. PhoneGap Developer App

Which version of iOS are running on your iPhone 6?

**Comment by lbranton** [comment] 2016-03-14 15:54
I'm having the same trouble and receiving "Unable to download archive from this server.  Please enter a valid url to connect to" error. I have also checked the IP address and it's correct. I am on a corporate network and I have also tried using a VPN. Is this the reason it won't work?

**Comment by hermwong** [comment] 2016-03-14 17:42
@lbranton from our experiences, we've found that corporate networks and VPN can sometimes have security policies that block the zip file being served from the PhoneGap Desktop to the PhoneGap Developer App.

If you're also running a firewall or AV software, they could also be blocking the serving of the zip file from the PhoneGap Desktop to the PhoneGap Developer App.

**Comment by Aleksandaarrr** [comment] 2016-03-15 11:12
I have tried on Win10 with firewall and AV and everything works fine, on Mac OSX without any firewall and AV it does not work..

**Comment by hermwong** [comment] 2016-03-17 21:55
@Aleksandaarrr could you provide some more info regarding the config on your Mac?

What is the messaging on the error that you receive?

**Comment by Aleksandaarrr** [comment] 2016-03-17 23:03
There is no error except the error on the phone (Downloading.. And then error), it won't connect to my MBP. Before android s6 could connect but now none of them can connect, but on my PC with windows and AV and firewalls it works perfectly... Phonegap does not log anything either so I don't know what is wrong

**Comment by hermwong** [comment] 2016-03-17 23:44
@Aleksandaarrr does your MBP have AV or firewall enabled?

It could be working on your Windows PC because the necessary ports are not being blocked (or they have been configured to allow access to those ports) by the AV / firewall software.

**Comment by Aleksandaarrr** [comment] 2016-03-17 23:47
No it does not have any AV or firewall enabled, nothing change when I turn on/off the firewall in settings

**Comment by hermwong** [comment] 2016-03-17 23:59
Other things that could potentially lead to connection issues:

1. VPN or being on a corporate network - sometimes the security policies for VPN / corporate network will block the zip file that is being served from the PhoneGap Desktop App to PhoneGap Developer App.
1. make sure you have latest version of PhoneGap Desktop (0.2.3) and PhoneGap Developer App (1.5.12)
1. corporate wifi profile on iPhone can sometimes cause connection issues between Desktop App and Developer App.
1. if you have VM or mutliple network adapters make sure you are using correct IP address (https://github.com/phonegap/phonegap-app-desktop/issues/396#issuecomment-150895870)

**Comment by Aleksandaarrr** [comment] 2016-03-18 09:23
I forgot to say that when i scanned ports on my MBP with phonegap running, port 3000 was open and when phonegap was closed it was not open, but still I can not connect

**Comment by aceso** [comment] 2016-05-16 18:29
I have the same problem. I am able to connect to the desktop url from the desktop itself. It says device is ready with a green icon. But connecting from the phone, it keeps alternating "Downloading"   and ""Tap to cancel" for about 10 times, and then it concludes with the error:  "Download error" and then shows an Alert window "Unable to download archive from the server. Please enter a valid url to connect to. " with OK button. My firewall is turned off, and as I said I am able to go to desktop url from a desktop browser. I am able to connect from another MAC desktop. But not from my iPhone6.

**Comment by wojjas** [comment] 2016-05-17 08:17
I had the same problem, with the phonegap CLI. 
**I solved it**!
Running on a MBP El Capitan, and iPhone6s, everything latest and greatest. Firewall off, no AV.

Phonegap tried to connect for a while then displaying that it failed and sugests to "enter a valid url to connect to" exactly as described above by @aceso.

I noticed that my network connection is unusually slow. Almost useless, about 0.5-1.5 Mb/s (should be around 50) When I restarted my comp. Network was as expected and everything worked just fine!
"Downloading" and ""Tap to cancel" a couple of times, in my console where I wrote "phonegap serve" I got "[phonegap] 200 /__api__/appzip" twice and then I had my app on my iPhone!

I managed to reproduce the problem and thus suspect the cause:
I started ios simulator (some XCode utility) by running:  ionic emulate ios, and then phonegap serve and the problem is back again! Also my internet connection is very slow. I quit ios-simulator, after a while my network connection for MBP was fine again and everything works!

I'm new to ionic, phonegap and dev on mobile devices so I can't give a correct answer to exactly what is wrong and why, sorry for that. But for me it was my laptop's internet-connection, it was too slow most likely caused by running ios-simulator.

Hope this helps :-)

**Comment by edukondalu123** [comment] 2017-04-24 07:11
I am also facing same problem.
I have turned off firewall. no AV
Using phonegap desktop app **latest** version and developer app also **latest**.
I have run phonegap desktop app in my **windows 8.1 pc** and i am testing it from my **iphone 10.3.1**
Any help

**Comment by edukondalu123** [comment] 2017-04-24 08:46
@jcesarmobile , @hermwong 
Any help from your side

**Comment by jcesarmobile** [comment] 2017-04-24 08:53
Make sure both the windows pc and the iPhone are connected to the same wifi.

**Comment by edukondalu123** [comment] 2017-04-24 08:58
yes, i did

**Comment by edukondalu123** [comment] 2017-04-24 09:37
I can provide error links from my iphone. Please find below

![211530 img_20170424_145712](https://cloud.githubusercontent.com/assets/20127057/25330911/e3585ec8-28fe-11e7-9581-da33b9ca984b.jpg)
![211531 img_20170424_145719](https://cloud.githubusercontent.com/assets/20127057/25330913/e3720986-28fe-11e7-8b0f-e87bc2e70e5e.jpg)
![211532 img_20170424_145720](https://cloud.githubusercontent.com/assets/20127057/25330912/e3650556-28fe-11e7-9c0b-e5f579ef72c7.jpg)

**Comment by edukondalu123** [comment] 2017-04-24 09:42
Is it bug for ios 10 or later?

**Comment by surajpindoria** [comment] 2017-04-24 18:25
Take a look at this [FAQ](http://docs.phonegap.com/references/developer-app/troubleshoot-faq/), there are a bunch of suggestions that may help you.

**Comment by surajpindoria** [comment] 2017-05-02 22:57
Going to close this off. If you are still seeing this please feel free to reopen.

**Closed by surajpindoria** 2017-05-02 22:57 UTC
Labels: user support

**Comment by carivadeneira** [comment] 2017-05-09 16:52
anybody could solve this error please help

**Comment by surajpindoria** [comment] 2017-05-09 17:09
@carivadeneira Did you try the FAQ link that I posted above? It has some tips that could cause connection issues.

**Comment by carivadeneira** [comment] 2017-05-09 18:01
@surajpindoria yes I tried but it did not help me do you have another solution

**Comment by surajpindoria** [comment] 2017-05-09 18:29
Unfortunately we don't have anything beyond that right now. It is a very difficult problem to debug without being able to reproduce it ourselves.

**Comment by dominickhacnguyen** [comment] 2017-08-14 17:20
Hi @carivadeneira , I see you're using Windows 10 as well.
- First, please try following the steps in Phonegap's troubleshooting documentation.
http://docs.phonegap.com/references/developer-app/troubleshoot-faq/
- After completing those steps and if you're still having problems, can you check to see if you enabled making your PC discoverable to other devices? 
http://www.digitalcitizen.life/how-set-your-networks-location-private-or-public-windows-10.
This was a simple error that I had overlooked and was the root issue in my case.

**Comment by Jonkat323** [comment] 2020-01-07 10:12
I have been using Phonegap for a long time and only started experiencing this issue when moving to my new house with a new internet connection. Changing my laptop's WiFi connection network profile from private to public did the trick.
