### ISSUE TITLE
Error: Uncaught, unspecified "error" event.(█[1m█[31m Error from Cordova Fetch: failed to get absolute path to installed module)

### ISSUE THREAD

**Issue by simovigi** [phonegap/phonegap-app-desktop#891] opened 2018-07-25 14:05 UTC
### PhoneGap Desktop version
v. 0.4.5
### Computer OS version
Win 10 Home
Version 1803
OS build 17134.112
### Network Type (home/corporate)
home
### Is your network using a proxy?
no
### Computer / Network security (firewall / anti-virus / disk encryption)
y
### Are you using VMs on your computer?
no
### Do you have multiple network adapters (or virtual network adapters)?
y
### Are you using VPN?
n
### Expected Behaviour
Creating new project
### Actual Behaviour
returns "Error: Uncaught, unspecified "error" event.(█[1m█[31m Error from Cordova Fetch: failed to get absolute path to installed module)"
#### Error message
Error: Uncaught, unspecified "error" event.(█[1m█[31m Error from Cordova Fetch: failed to get absolute path to installed module)

![screenshot 69](https://user-images.githubusercontent.com/23078301/43205904-bdc2906e-9024-11e8-8d8e-19ea580a40c7.png)

**Comment by yorchbiker** [comment] 2018-09-04 22:41
Hi, could you solve this issue? I'm having the same

**Comment by purplecabbage** [comment] 2018-09-07 19:47
I cannot reproduce this so far.
Does this happen every time, or occasionally?
Does the app crash and you need to restart it? or does it recover?
Can you open the Developer Console from the menu: `Menu->Help->Developer Console` and report the text that is output to the 'console' tab?

**Comment by yorchbiker** [comment] 2018-09-07 20:12
Thank you to answer purplecabbage,

It seems it was a registration server error; I restarted the computer twice and the problem fixed.

**Comment by purplecabbage** [comment] 2018-09-07 21:30
I am closing this, assuming that it was a one-off issue.
@simovigi if you still experience this, please reopen it.

**Closed by purplecabbage** 2018-09-07 21:30 UTC
