### ISSUE TITLE
selected folder does not contain config.xml and Server Offline. 

### ISSUE THREAD

**Issue by Le8080** [phonegap/phonegap-app-desktop#409] opened 2015-07-28 21:40 UTC
I am trying to use phonegap-app-dektop but unfortunately still no success. Directories .cordova, hooks, platforms, plugins are all empty when i tried to create new project. 

I am using windows 7, have internet access, firewall is off.
please help
![capture](https://cloud.githubusercontent.com/assets/13539860/8944614/44fa13aa-35b4-11e5-8cf3-d3e94c6048a1.PNG)
![capture1](https://cloud.githubusercontent.com/assets/13539860/8944615/450a907c-35b4-11e5-91b0-8d9f44ab329c.PNG)

**Comment by hermwong** [comment] 2015-08-03 20:32
You could try resetting the templates by:

1. exit the PhoneGap Desktop App
1. delete the 4 folders `.cordova`, `hooks`, `platforms` and `plugins`
1. make sure you have firewall turned off and Internet access
1. launch the PhoneGap Desktop App

**Comment by hermwong** [comment] 2015-09-29 22:49
Duplicate of #322

**Closed by hermwong** 2015-09-29 22:49 UTC
Labels: user support
