### ISSUE TITLE
phonegap will not open correctly

### ISSUE THREAD

**Issue by rrizk01** [phonegap/phonegap-app-desktop#372] opened 2015-06-14 03:41 UTC
I am in the process of trying to download PhoneGap to my desktop (Windows 7) I tried 0.1.7 and 0.1.6 versions - none are working. I have run the "npm install -g phonegap" instruction in node.js and I get the following in the logs - Im not sure if the warnings are the reason why phonegap interface wont open - all that opens is a node.webkit interface (
![webkit interface](https://cloud.githubusercontent.com/assets/12878648/8146989/f6e6c83e-129a-11e5-8d41-4e6ca2475fdd.jpg)
 rather than phonegap.

![node js images](https://cloud.githubusercontent.com/assets/12878648/8146987/d7053514-129a-11e5-85d1-00d172e21434.jpg)

**Comment by hermwong** [comment] 2015-06-18 16:02
Duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/362

**Comment by rrizk01** [comment] 2015-07-02 06:33
Version 0.1.6 diesnt work either. Are you available for a google hangout session to discuss my difficulties please? 
Many thanks, Rosemary 


Sent from my Samsung device

-------- Original message --------

**Comment by mootieman** [comment] 2015-07-10 19:47
Do we have a solution to this yet? I've got the same issue - PhoneGap Desktop won't open - it just opens to the screen above.

**Comment by hermwong** [comment] 2015-07-10 19:48
No solution yet. We haven't been able to reproduce this issue on our end.

**Comment by mootieman** [comment] 2015-07-10 19:51
How can I help you identify the cause? - Are there logs or something that I can send you?

I have phonegap working on my desktop - but it gives this error on the laptop.

**Comment by hermwong** [comment] 2015-07-10 20:51
Can you provide the following info:

1. operating system?
1. firewall or anti-virus software enabled on computer?
1. hard disk encryption software enabled?
1. are you behind a network based firewall (corporate network, router with a firewall)?
1. are you on a corporate network?

**Comment by FoxwoodDesign** [comment] 2015-07-13 12:23
Hi, 

Has anyone found a solution to this yet? I have disabled all firewalls and not behind a network.

Tried on Win7 and Win8... It just loads with the NW.JS window.

I've tried 0.1.6 and 0.1.7

Please help.

**Comment by hermwong** [comment] 2015-07-14 18:40
No solution yet. It seems to be an issue in nwjs/node-webkit https://github.com/gitterHQ/desktop/issues/59

**Comment by hermwong** [comment] 2015-07-15 17:08
Closing since this is a duplicate of: https://github.com/phonegap/phonegap-app-desktop/issues/362

**Closed by hermwong** 2015-07-15 17:08 UTC
Labels: duplicate, user support

**Comment by hermwong** [comment] 2015-08-13 17:42
Please see: https://github.com/phonegap/phonegap-app-desktop/issues/362#issuecomment-130775883

**Comment by hermwong** [comment] 2015-09-30 13:18
[PhoneGap Desktop 0.1.11](https://github.com/phonegap/phonegap-app-desktop/releases/tag/0.1.11) should fix this issue. Please leave any feedback in #362.
