### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by Tr0j4n9** [phonegap/phonegap-app-desktop#849] opened 2017-08-29 23:50 UTC
## _System Configuration_
Better than windows

### PhoneGap Desktop version
???

### PhoneGap Mobile App version
???

### Mobile devices & Mobile OS version
???

### Computer OS version
Linux Mint 18.2 KDE 5.8.7 (5.36.0)
QT version 5.6.1
Kernel 4.8.0-53-generic (64-bit)

### Network Type (home/corporate)
Home.

### Is your network using a proxy?
No.

### Computer / Network security (firewall / anti-virus / disk encryption)
None that will concern.

### Are you using VMs on your computer?
No.

### Do you have multiple network adapters (or virtual network adapters)?
No.

### Are you using VPN?
No.

### Expected Behaviour
Works on Linux.

### Actual Behaviour
Does not work on Linux.

### Steps to Reproduce 
Try to install on Linux.

#### Error messages
???

**Comment by surajpindoria** [comment] 2017-08-29 23:56
Duplicate of https://github.com/phonegap/phonegap-app-desktop/issues/249#issuecomment-298102898

**Closed by surajpindoria** 2017-08-29 23:56 UTC
Labels: duplicate
