### ISSUE TITLE
Broken Buttons (Images) on PhoneGap Desktop

### ISSUE THREAD

**Issue by amin2009** [phonegap/phonegap-app-desktop#444] opened 2015-09-18 19:49 UTC
I installed "PhoneGap-Desktop-Beta-0.1.2-win". All the buttons looks broken image (Screenshot attached).
- Note1 : version 0.1.8 doesn't working here, it opens "NW.JS" window.
- Note2 : Reinstall didn't resolve it.
- Note3: My PC: Win-8.1-Pro-64bit / i5 / 8GB RAM / Norton Antivirus installed 

Please advice, how can I resolve the broken button image issue.

![phonegap-buttons-broken-102](https://cloud.githubusercontent.com/assets/1782378/9969476/86c1ea12-5e70-11e5-8593-39e31847bc82.png)

**Comment by amin2009** [comment] 2015-09-18 21:43
Installed version 0.1.10, not resolved.

**Comment by hermwong** [comment] 2015-09-24 21:55
duplicate of: #309

**Comment by hermwong** [comment] 2015-09-24 21:56
Locking issue, please keep all discussion in the #309 comments.

**Closed by hermwong** 2015-09-24 21:56 UTC
Labels: bug, windows
