### ISSUE TITLE
Console does not autoscroll

### ISSUE THREAD

**Issue by EffEPi** [phonegap/phonegap-app-desktop#504] opened 2015-12-07 02:06 UTC
I am doing some console.log and it is a pain to be able to follow it.

A checkbox that allows auto-scroll would be great, and maybe even a way to "clear" it.

also, every "console.log('msg');" shows `undefined msg`

**Comment by hermwong** [comment] 2015-12-07 18:48
Duplicate of #263.

Closing & locking so that we can keep all discussion regarding this issue within the comments of #263.

**Closed by hermwong** 2015-12-07 18:48 UTC
