### ISSUE TITLE
PhoneGap 0.4.2 also fails with Mac OS Sierra

### ISSUE THREAD

**Issue by erhanyasar** [phonegap/phonegap-app-desktop#746] opened 2016-12-09 16:31 UTC
I'm not specifying any system info bcs of #724 and I tried even formatting just right after today's new release. Not able to make it work installing right after format of Mac OS Sierra. Besides it wasn't possible to make it update happen with the upcoming pop-up when the desktop app is working.

**Comment by hemademedoit** [comment] 2016-12-10 17:53
I went back to 0.4.1 since 0.4.2 wasn't starting. A fix coming soon?

**Comment by surajpindoria** [comment] 2016-12-12 10:50
Closing this, duplicate of #724

**Closed by surajpindoria** 2016-12-12 10:50 UTC
